const fs=require('node:fs')
const test=require('node:test')
const assert=require('node:assert/strict')
const ts=require('typescript')

require.extensions['.ts']=(module,filename)=>{const source=fs.readFileSync(filename,'utf8'),output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;module._compile(output,filename)}

const {addDays,fromISO,toISO}=require('../lib/calendar/date.ts')
const {applyScopedUpdate,createSeries,normalizedRule,recurrenceLabel,recurrenceMode,removeScoped}=require('../lib/calendar/recurrence.ts')

const base={id:'event',date:'2026-07-13',start:9,end:10,title:'Standup',categoryId:'work',layer:'plan'}
const makeSeries=()=>createSeries(base,normalizedRule(base,'multiple',[0,1,3],5))
const plusDays=(iso,days)=>toISO(addDays(fromISO(iso),days))
const assertLinked=(blocks,original)=>{assert.equal(new Set(blocks.map(block=>block.seriesId)).size,1);assert.deepEqual(blocks.map(block=>block.id),original.map(block=>block.id));assert.deepEqual(blocks.map(block=>block.occurrenceIndex),original.map(block=>block.occurrenceIndex));assert.deepEqual(blocks.map(block=>[block.recurrenceDate,block.recurrenceStart,block.recurrenceEnd]),original.map(block=>[block.recurrenceDate,block.recurrenceStart,block.recurrenceEnd]));for(const block of blocks)assert.equal(removeScoped(blocks,block,'all').length,0)}

test('multiple days creates exactly Monday, Tuesday, and Thursday for five weeks',()=>{const rule=normalizedRule(base,'multiple',[0,1,3],5),series=createSeries(base,rule);assert.equal(recurrenceMode(rule),'multiple');assert.equal(recurrenceLabel(rule),'Every week on Monday, Tuesday, Thursday for 5 weeks');assert.equal(series.length,15);assert.deepEqual(series.slice(0,6).map(block=>block.date),['2026-07-13','2026-07-14','2026-07-16','2026-07-20','2026-07-21','2026-07-23']);assert.equal(series.at(-1).date,'2026-08-13');assert.ok(series.every(block=>block.recurrenceDate===block.date&&block.recurrenceStart===9&&block.recurrenceEnd===10))})

test('multiple days permits the event creation day as the only selected weekday',()=>{const rule=normalizedRule(base,'multiple',[0],3),series=createSeries(base,rule);assert.equal(series.length,3);assert.deepEqual(series.map(block=>block.date),['2026-07-13','2026-07-20','2026-07-27'])})

test('daily duration adds weeks and days without an upper limit',()=>{const rule=normalizedRule(base,'daily',[],60,3),series=createSeries(base,rule);assert.equal(rule.weeks,60);assert.equal(rule.days,3);assert.equal(series.length,423);assert.equal(recurrenceLabel(rule),'Every day for 423 days');assert.equal(series.at(-1).date,plusDays(base.date,422))})

test('an unselected start weekday is not inserted into the series',()=>{const sunday={...base,date:'2026-07-12'},series=createSeries(sunday,normalizedRule(sunday,'multiple',[0,1,3],5));assert.equal(series.length,15);assert.equal(series[0].date,'2026-07-13');assert.ok(!series.some(block=>block.date==='2026-07-12'))})

test('following move is absolute after a single-occurrence time exception',()=>{const series=makeSeries(),selected=series[3],withException=applyScopedUpdate(series,selected,{...selected,start:10,end:11},'only'),exception=withException.find(block=>block.id===selected.id),followingIds=new Set(series.slice(3).map(block=>block.id)),updated=applyScopedUpdate(withException,exception,{...exception,start:9.5,end:10.5},'following');for(const block of updated){if(followingIds.has(block.id)){assert.equal(block.start,9.5);assert.equal(block.end,10.5)}else{assert.equal(block.start,9);assert.equal(block.end,10)}}})

test('legacy recurring events gain canonical schedule values before an exception is made',()=>{const legacy=makeSeries().map(({recurrenceDate,recurrenceStart,recurrenceEnd,...block})=>block),selected=legacy[3],withException=applyScopedUpdate(legacy,selected,{...selected,date:plusDays(selected.date,1),start:10,end:11},'only'),exception=withException.find(block=>block.id===selected.id),updated=applyScopedUpdate(withException,exception,{...exception,date:plusDays(selected.date,2)},'following');assert.ok(withException.every(block=>block.recurrenceDate&&block.recurrenceStart===9&&block.recurrenceEnd===10));assert.equal(updated.find(block=>block.id===selected.id).date,plusDays(selected.date,2));assert.equal(updated.find(block=>block.id===legacy[4].id).date,plusDays(legacy[4].date,2))})

test('all-events move is absolute after a single-occurrence time exception',()=>{const series=makeSeries(),selected=series[4],withException=applyScopedUpdate(series,selected,{...selected,start:10,end:11},'only'),exception=withException.find(block=>block.id===selected.id),updated=applyScopedUpdate(withException,exception,{...exception,start:9.25,end:10.25},'all');assert.ok(updated.every(block=>block.start===9.25&&block.end===10.25))})

test('all-events move replaces every prior time exception with the selected final slot',()=>{const series=makeSeries(),second=series[1],fourth=series[3],withException=applyScopedUpdate(series,second,{...second,start:10,end:11},'only'),selected=withException.find(block=>block.id===fourth.id),updated=applyScopedUpdate(withException,selected,{...selected,start:10,end:11},'all');for(const block of updated){assert.equal(block.start,10);assert.equal(block.end,11);assert.equal(block.recurrenceStart,9);assert.equal(block.recurrenceEnd,10)}})

test('successive following moves never decouple the original repeating set',()=>{const series=makeSeries(),second=series[1],third=series[2],fourth=series[3],afterSecond=applyScopedUpdate(series,second,{...second,start:10,end:11},'following'),currentThird=afterSecond.find(block=>block.id===third.id),afterThird=applyScopedUpdate(afterSecond,currentThird,{...currentThird,start:11,end:12},'following'),currentFourth=afterThird.find(block=>block.id===fourth.id),updated=applyScopedUpdate(afterThird,currentFourth,{...currentFourth,start:12,end:13},'all');assert.equal(new Set(updated.map(block=>block.seriesId)).size,1);assert.ok(updated.every(block=>block.start===12&&block.end===13));assert.equal(removeScoped(updated,updated[0],'all').length,0)})

test('three following moves then an all-events move normalize the entire series to event five',()=>{const original=makeSeries();let blocks=original;for(const [index,start] of [[1,10],[2,11],[3,12]]){const selected=blocks[index];blocks=applyScopedUpdate(blocks,selected,{...selected,start,end:start+1},'following')}assert.deepEqual(blocks.slice(0,5).map(block=>block.start),[9,10,11,12,12]);const fifth=blocks[4],target={...fifth,start:12.5,end:13.5};blocks=applyScopedUpdate(blocks,fifth,target,'all');assertLinked(blocks,original);assert.ok(blocks.every(block=>block.start===target.start&&block.end===target.end))})

test('series identity and ordering survive mixed scoped edit sequences',()=>{const original=makeSeries();let blocks=original,selected=blocks[2];blocks=applyScopedUpdate(blocks,selected,{...selected,start:10,end:11},'only');assertLinked(blocks,original);selected=blocks[1];blocks=applyScopedUpdate(blocks,selected,{...selected,end:11.5},'following');assertLinked(blocks,original);selected=blocks[4];blocks=applyScopedUpdate(blocks,selected,{...selected,date:plusDays(selected.recurrenceDate,2)},'following');assertLinked(blocks,original);selected=blocks[6];blocks=applyScopedUpdate(blocks,selected,{...selected,title:'Linked forever'},'all');assertLinked(blocks,original)})

test('all pairs of successive following cuts are normalized by a later all-events move',()=>{for(let firstCut=0;firstCut<6;firstCut++)for(let secondCut=0;secondCut<6;secondCut++){const original=makeSeries();let blocks=original,selected=blocks[firstCut];blocks=applyScopedUpdate(blocks,selected,{...selected,start:selected.recurrenceStart+.5,end:selected.recurrenceEnd+.5},'following');assertLinked(blocks,original);selected=blocks[secondCut];blocks=applyScopedUpdate(blocks,selected,{...selected,start:selected.recurrenceStart+.75,end:selected.recurrenceEnd+.75},'following');assertLinked(blocks,original);selected=blocks[3];const targetStart=selected.recurrenceStart+.25,targetEnd=selected.recurrenceEnd+.25;blocks=applyScopedUpdate(blocks,selected,{...selected,start:targetStart,end:targetEnd},'all');assertLinked(blocks,original);assert.ok(blocks.every(block=>block.start===targetStart&&block.end===targetEnd))}})

test('all three-following permutations preserve scope boundaries and normalize from every all-events source',()=>{for(let firstCut=0;firstCut<6;firstCut++)for(let secondCut=0;secondCut<6;secondCut++)for(let thirdCut=0;thirdCut<6;thirdCut++){const original=makeSeries();let blocks=original;for(const [cut,targetStart] of [[firstCut,9.5],[secondCut,10.25],[thirdCut,11.75]]){const before=blocks,selected=before[cut];blocks=applyScopedUpdate(before,selected,{...selected,start:targetStart,end:targetStart+1},'following');for(let index=0;index<blocks.length;index++){assert.equal(blocks[index].start,index>=cut?targetStart:before[index].start);assert.equal(blocks[index].end,index>=cut?targetStart+1:before[index].end)}assertLinked(blocks,original)}for(let source=0;source<6;source++){const selected=blocks[source],targetStart=12.5+source/4,updated=applyScopedUpdate(blocks,selected,{...selected,start:targetStart,end:targetStart+1},'all');assertLinked(updated,original);assert.ok(updated.every(block=>block.start===targetStart&&block.end===targetStart+1))}}})

test('all-events date move removes prior date offsets while preserving recurrence spacing',()=>{const series=makeSeries(),second=series[1],withException=applyScopedUpdate(series,second,{...second,date:plusDays(second.date,2)},'only'),fifth=withException[4],updated=applyScopedUpdate(withException,fifth,{...fifth,date:plusDays(fifth.recurrenceDate,1)},'all');for(let index=0;index<updated.length;index++){assert.equal(updated[index].date,plusDays(series[index].recurrenceDate,1));assert.equal(updated[index].recurrenceDate,series[index].recurrenceDate)}})

test('cross-day following moves keep immutable anchors and cannot collapse adjacent occurrences',()=>{const dailyBase={...base,start:13.5,end:14.5},original=createSeries(dailyBase,normalizedRule(dailyBase,'daily',[],1));let blocks=original,second=blocks[1];blocks=applyScopedUpdate(blocks,second,{...second,date:plusDays(second.date,-1),start:11.5,end:12.5},'following');const first=blocks[0];blocks=applyScopedUpdate(blocks,first,{...first,date:plusDays(first.date,1),start:11.5,end:12.5},'following');assertLinked(blocks,original);assert.deepEqual(blocks.map(block=>block.date),original.map(block=>plusDays(block.date,1)));assert.deepEqual(blocks.map(block=>block.recurrenceDate),original.map(block=>block.recurrenceDate));assert.equal(new Set(blocks.map(block=>`${block.date}:${block.start}:${block.end}`)).size,blocks.length);assert.ok(blocks.every(block=>block.start===11.5&&block.end===12.5))})

test('cross-day following permutations always rebuild their scope from immutable anchors',()=>{const shifts=[-2,-1,1,2];for(let firstCut=0;firstCut<5;firstCut++)for(const firstShift of shifts)for(let secondCut=0;secondCut<5;secondCut++)for(const secondShift of shifts){const dailyBase={...base,start:13.5,end:14.5},original=createSeries(dailyBase,normalizedRule(dailyBase,'daily',[],1)),first=original[firstCut];const afterFirst=applyScopedUpdate(original,first,{...first,date:plusDays(first.recurrenceDate,firstShift)},'following'),second=afterFirst[secondCut],secondTarget=plusDays(second.recurrenceDate,secondShift);if(second.date===secondTarget)continue;const afterSecond=applyScopedUpdate(afterFirst,second,{...second,date:secondTarget},'following');assertLinked(afterSecond,original);for(let index=0;index<afterSecond.length;index++)assert.equal(afterSecond[index].date,index>=secondCut?plusDays(original[index].recurrenceDate,secondShift):afterFirst[index].date)}})

test('non-schedule all-events edits preserve existing time exceptions',()=>{const series=makeSeries(),second=series[1],withException=applyScopedUpdate(series,second,{...second,start:10,end:11},'only'),selected=withException[4],updated=applyScopedUpdate(withException,selected,{...selected,title:'Renamed together'},'all');assert.ok(updated.every(block=>block.title==='Renamed together'));assert.equal(updated[1].start,10);assert.equal(updated[1].end,11);assert.ok(updated.filter((_,index)=>index!==1).every(block=>block.start===9&&block.end===10))})

test('only and following deletes retain one identity for every remaining occurrence',()=>{const original=makeSeries(),onlyRemoved=removeScoped(original,original[3],'only'),followingRemoved=removeScoped(original,original[8],'following');assert.equal(onlyRemoved.length,original.length-1);assert.equal(new Set(onlyRemoved.map(block=>block.seriesId)).size,1);for(const block of onlyRemoved)assert.equal(removeScoped(onlyRemoved,block,'all').length,0);assert.equal(followingRemoved.length,8);assert.equal(new Set(followingRemoved.map(block=>block.seriesId)).size,1);for(const block of followingRemoved)assert.equal(removeScoped(followingRemoved,block,'all').length,0)})

test('scoped updates cannot overwrite immutable recurrence identity fields',()=>{const original=makeSeries(),selected=original[2],tampered={...selected,seriesId:'different-set',occurrenceIndex:999,start:10,end:11},only=applyScopedUpdate(original,selected,tampered,'only'),all=applyScopedUpdate(original,selected,tampered,'all');assertLinked(only,original);assertLinked(all,original)})

test('following date move uses immutable canonical dates without severing set identity',()=>{const series=makeSeries(),selected=series[3],canonical=selected.recurrenceDate,withException=applyScopedUpdate(series,selected,{...selected,date:plusDays(selected.date,1)},'only'),exception=withException.find(block=>block.id===selected.id),followingIds=new Set(series.slice(3).map(block=>block.id)),updated=applyScopedUpdate(withException,exception,{...exception,date:plusDays(canonical,2)},'following');for(const block of updated.filter(block=>followingIds.has(block.id))){const original=series.find(item=>item.id===block.id);assert.equal(block.date,plusDays(original.recurrenceDate,2));assert.equal(block.recurrenceDate,original.recurrenceDate)}assertLinked(updated,series)})

test('following resize is absolute after a single-occurrence resize exception',()=>{const series=makeSeries(),selected=series[3],withException=applyScopedUpdate(series,selected,{...selected,end:11},'only'),exception=withException.find(block=>block.id===selected.id),followingIds=new Set(series.slice(3).map(block=>block.id)),updated=applyScopedUpdate(withException,exception,{...exception,end:10.5},'following');for(const block of updated){assert.equal(block.start,9);assert.equal(block.end,followingIds.has(block.id)?10.5:10)}})

test('following title edit preserves existing time exceptions while applying one title',()=>{const series=makeSeries(),selected=series[3],withException=applyScopedUpdate(series,selected,{...selected,start:10,end:11},'only'),exception=withException.find(block=>block.id===selected.id),followingIds=new Set(series.slice(3).map(block=>block.id)),updated=applyScopedUpdate(withException,exception,{...exception,title:'Renamed'},'following');for(const block of updated){assert.equal(block.title,followingIds.has(block.id)?'Renamed':'Standup')}assert.equal(updated.find(block=>block.id===selected.id).start,10);assert.equal(updated.find(block=>block.id===series[4].id).start,9)})

test('delete scopes remove only, following, or all intended occurrences',()=>{const series=makeSeries(),selected=series[5];assert.equal(removeScoped(series,selected,'only').length,14);assert.equal(removeScoped(series,selected,'following').length,5);assert.equal(removeScoped(series,selected,'all').length,0)})

test('recurrence controls keep the requested order, defaults, duration fields, and circular weekdays',()=>{const editor=fs.readFileSync(require.resolve('../components/calendar/RecurrenceEditor.tsx'),'utf8'),css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8'),multiple=editor.indexOf('<option value="multiple">Multiple days a week</option>'),weekly=editor.indexOf('<option value="weekly">Every week</option>'),daily=editor.indexOf('<option value="daily">Every day</option>');assert.ok(multiple>0&&multiple<weekly&&weekly<daily);assert.ok(!editor.includes('placeholder=')&&!editor.includes('Choose at least two days')&&!editor.includes('Enter a duration'));assert.match(editor,/next==='multiple'\?\[createdDay\]:\[\]/);assert.match(editor,/aria-label="Repeat weeks"/);assert.match(editor,/aria-label="Repeat days"/);assert.match(css,/\.weekday-picker button\{width:26px;height:26px;aspect-ratio:1;padding:0;[^}]*border-radius:50%/)})

test('live inspector edits remember one recurring scope per selection session',()=>{const app=fs.readFileSync(require.resolve('../components/calendar/CalendarApp.tsx'),'utf8');assert.match(app,/editScopeRef=useRef/);assert.match(app,/remembered=editScopeRef\.current/);assert.ok(!app.includes('[editScope,setEditScope]'))})
