const fs=require('node:fs')
const path=require('node:path')
const Module=require('node:module')
const test=require('node:test')
const assert=require('node:assert/strict')
const ts=require('typescript')

require.extensions['.ts']=(module,filename)=>{const source=fs.readFileSync(filename,'utf8'),output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;module._compile(output,filename)}
const resolveFilename=Module._resolveFilename
Module._resolveFilename=(request,parent,isMain,options)=>resolveFilename(request.startsWith('@/')?path.join(__dirname,'..',request.slice(2)):request,parent,isMain,options)

const {mergeSnapshots}=require('../lib/supabase/merge.ts')
const {applyDatabaseDelta,parseDatabaseDelta}=require('../lib/supabase/sync.ts')
const {sparseRowChanges}=require('../lib/supabase/rows.ts')
const {diffSnapshots,toDatabaseSnapshot}=require('../lib/supabase/database.ts')

const snapshot=()=>({revision:4,account:{settings:{wakeHour:7,sleepHour:22,snapMinutes:15,defaultDuration:60,hourScale:64,showWeekends:true,timeFormat:'12h',underlayOpacity:40,defaultCategoryId:'work'},quote_bank:['Focus'],current_quote:'Focus'},groups:[{id:'group',name:'Main',position:0}],calendars:[{id:'work',group_id:'group',name:'Work',color:'#123456',is_visible:true,position:0,deleted_at:null}],series:[],blocks:[{id:'block',category_id:'work',date:'2026-07-14',start_minute:540,end_minute:600,title:'Plan',layer:'plan',all_day:false,source_plan_id:null,status:null,series_id:null,occurrence_index:null,recurrence_date:null,recurrence_start_minute:null,recurrence_end_minute:null}],blockNotes:[{id:'block',content:'Plan details'}],todoTabs:[{id:'inbox',name:'Inbox',is_favorite:false,position:0}],todoItems:[{id:'task',tab_id:'inbox',parent_id:null,title:'Task',expected_minutes:null,is_completed:false,position:0}],todoItemNotes:[{id:'task',content:'Task details'}],todoLinks:[{id:'7461736b00626c6f636b',item_id:'task',block_id:'block'}]})
const patch=(overrides={})=>({account:null,upsert_groups:[],delete_group_ids:[],upsert_calendars:[],delete_calendar_ids:[],upsert_series:[],delete_series_ids:[],upsert_blocks:[],delete_block_ids:[],upsert_block_notes:[],delete_block_note_ids:[],upsert_todo_tabs:[],delete_todo_tab_ids:[],upsert_todo_items:[],delete_todo_item_ids:[],upsert_todo_item_notes:[],delete_todo_item_note_ids:[],upsert_todo_links:[],delete_todo_link_ids:[],...overrides})
const delta=(from,to,changes={})=>({from_revision:from,to_revision:to,patch:patch(changes)})

test('the shared sparse diff emits only changed fields for an existing note or event',()=>{const before=[{id:'event',title:'Plan',content:'Old note',start:540}],after=[{id:'event',title:'Plan',content:'New note',start:540}],changes=sparseRowChanges(before,after);assert.deepEqual(changes.upserts,[]);assert.deepEqual(changes.updates,[{id:'event',content:'New note'}]);assert.deepEqual(changes.deletes,[])})

test('a task rename emits one sparse task field and does not rewrite settings or notes',()=>{const data={version:2,blocks:[],categories:[],groups:[],quoteBank:[],currentQuote:'',settings:{wakeHour:7,sleepHour:22,snapMinutes:15,defaultDuration:60,density:'default',hourScale:1,monthScale:1,defaultCategoryId:'',showWeekends:true,weekStartsOn:0,timeFormat:'12h',underlayOpacity:40,todoTabs:[{id:'inbox',name:'Inbox'}],todoItems:[{id:'task',tabId:'inbox',title:'Before',notes:'Keep this note'}]}},base=toDatabaseSnapshot(data,4),renamed=structuredClone(data);renamed.settings.todoItems[0].title='After';const changes=diffSnapshots(base,toDatabaseSnapshot(renamed,4));assert.equal(changes.account,null);assert.deepEqual(changes.update_todo_items,[{id:'task',title:'After'}]);assert.deepEqual(changes.update_todo_item_notes,[]);assert.deepEqual(changes.upsert_todo_item_notes,[])})

test('a task note edit transfers only its independently synchronized note row',()=>{const data={version:2,blocks:[],categories:[],groups:[],quoteBank:[],currentQuote:'',settings:{wakeHour:7,sleepHour:22,snapMinutes:15,defaultDuration:60,density:'default',hourScale:1,monthScale:1,defaultCategoryId:'',showWeekends:true,weekStartsOn:0,timeFormat:'12h',underlayOpacity:40,todoTabs:[{id:'inbox',name:'Inbox'}],todoItems:[{id:'task',tabId:'inbox',title:'Task',notes:'Before'}]}},base=toDatabaseSnapshot(data,4),edited=structuredClone(data);edited.settings.todoItems[0].notes='After';const changes=diffSnapshots(base,toDatabaseSnapshot(edited,4));assert.deepEqual(changes.update_todo_items,[]);assert.deepEqual(changes.update_todo_item_notes,[{id:'task',content:'After'}])})

test('to-do panel preferences use sparse account settings without rewriting normalized to-do rows',()=>{const data={version:2,blocks:[],categories:[],groups:[],quoteBank:[],currentQuote:'',settings:{wakeHour:7,sleepHour:22,snapMinutes:15,defaultDuration:60,density:'default',hourScale:1,monthScale:1,defaultCategoryId:'',showWeekends:true,weekStartsOn:0,timeFormat:'12h',underlayOpacity:40,todoPanelTitle:'To-do list',collapsedTodoTabIds:[],todoTabs:[{id:'inbox',name:'Inbox'}],todoItems:[]}},base=toDatabaseSnapshot(data,4),edited=structuredClone(data);edited.settings.todoPanelTitle='Tasks';edited.settings.collapsedTodoTabIds=['inbox'];const changes=diffSnapshots(base,toDatabaseSnapshot(edited,4));assert.deepEqual(changes.account,{settings:{todoPanelTitle:'Tasks',collapsedTodoTabIds:['inbox']}});assert.deepEqual(changes.upsert_todo_tabs,[]);assert.deepEqual(changes.update_todo_tabs,[])})

test('the to-do panel preference migration backfills typed account settings and advances sync revisions',()=>{const migration=fs.readFileSync(require.resolve('../supabase/migrations/20260804000000_sync_todo_panel_preferences.sql'),'utf8');assert.ok(migration.includes("'{todoPanelTitle}'"));assert.ok(migration.includes("'{collapsedTodoTabIds}'"));assert.ok(migration.includes('accounts_todo_panel_preferences_check'));assert.ok(migration.includes('revision = account.revision + 1, modified_revision = account.revision + 1'));assert.ok(migration.includes('workspace_storage_bytes(account.user_id)'))})

test('three-way merge combines independent event and note edits',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks[0].title='Local title';remote.blockNotes[0].content='Remote note';remote.revision=5;const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.revision,5);assert.equal(result.snapshot.blocks[0].title,'Local title');assert.equal(result.snapshot.blockNotes[0].content,'Remote note')})

test('three-way merge combines an independent task rename and task note edit',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.todoItems[0].title='Local task';remote.todoItemNotes[0].content='Remote task note';remote.revision=5;const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.todoItems[0].title,'Local task');assert.equal(result.snapshot.todoItemNotes[0].content,'Remote task note')})

test('three-way merge reports overlapping edits and keeps local as the proposed resolution',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks[0].title='Local title';remote.blocks[0].title='Remote title';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,['blocks.block.title']);assert.equal(result.snapshot.blocks[0].title,'Local title')})

test('delete versus edit is an explicit conflict',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks=[];remote.blocks[0].title='Remote title';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,['blocks.block']);assert.equal(result.snapshot.blocks.length,0)})

test('independent row changes merge without conflict',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks.push({...local.blocks[0],id:'local',title:'Local block'});remote.groups[0].name='Remote group';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.groups[0].name,'Remote group');assert.equal(result.snapshot.blocks.find(block=>block.id==='local').title,'Local block')})

test('independent settings fields merge without replacing the settings object',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.account.settings.hourScale=72;remote.account.settings.showWeekends=false;const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.account.settings.hourScale,72);assert.equal(result.snapshot.account.settings.showWeekends,false)})

test('object key order does not create false changes or conflicts',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.account.settings=Object.fromEntries(Object.entries(local.account.settings).reverse());remote.groups[0].name='Remote group';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.groups[0].name,'Remote group')})

test('server conflict choice keeps independent local note edits',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks[0].title='Local title';local.blockNotes[0].content='Local note';remote.blocks[0].title='Remote title';const result=mergeSnapshots(base,remote,local);assert.deepEqual(result.conflicts,['blocks.block.title']);assert.equal(result.snapshot.blocks[0].title,'Remote title');assert.equal(result.snapshot.blockNotes[0].content,'Local note')})

test('an empty delta advances the durable cursor without replacing cached rows',()=>{const base=snapshot(),next=applyDatabaseDelta(base,delta(4,7));assert.equal(next.revision,7);assert.deepEqual(next.account,base.account);assert.deepEqual(next.blocks,base.blocks);assert.notEqual(next.blocks,base.blocks)})

test('a delta replaces only changed rows and independently replaces only changed notes',()=>{const base=snapshot();base.blocks.push({...base.blocks[0],id:'untouched',title:'Untouched'});base.blockNotes.push({id:'untouched',content:'Cached detail'});const changed={...base.blocks[0],title:'Remote title'};const next=applyDatabaseDelta(base,delta(4,5,{upsert_blocks:[changed],upsert_block_notes:[{id:'block',content:'Remote note'}]}));assert.equal(next.revision,5);assert.equal(next.blocks.find(row=>row.id==='block').title,'Remote title');assert.equal(next.blockNotes.find(row=>row.id==='block').content,'Remote note');assert.equal(next.blockNotes.find(row=>row.id==='untouched').content,'Cached detail')})

test('delete tombstones remove only named rows',()=>{const base=snapshot();base.blocks.push({...base.blocks[0],id:'keep'});const next=applyDatabaseDelta(base,delta(4,6,{delete_block_ids:['block']}));assert.deepEqual(next.blocks.map(row=>row.id),['keep'])})

test('deleting an event removes cached task links without retransferring the task',()=>{const base=snapshot(),next=applyDatabaseDelta(base,delta(4,5,{delete_block_ids:['block']}));assert.deepEqual(next.todoItems,base.todoItems);assert.deepEqual(next.todoLinks,[])})

test('task deltas replace metadata and notes independently',()=>{const base=snapshot(),next=applyDatabaseDelta(base,delta(4,5,{upsert_todo_items:[{...base.todoItems[0],title:'Renamed'}]}));assert.equal(next.todoItems[0].title,'Renamed');assert.equal(next.todoItemNotes[0].content,'Task details')})

test('a checkpoint patch can atomically update every entity kind',()=>{const base=snapshot(),account={...base.account,current_quote:'Changed'},group={...base.groups[0],name:'Changed group'},calendar={...base.calendars[0],color:'#abcdef'},series={id:'series',recurrence:{frequency:'weekly',interval:1,weekdays:[2],weeks:2}},block={...base.blocks[0],id:'new',series_id:'series'};const next=applyDatabaseDelta(base,delta(4,8,{account,upsert_groups:[group],upsert_calendars:[calendar],upsert_series:[series],upsert_blocks:[block],delete_block_ids:['block']}));assert.equal(next.revision,8);assert.equal(next.account.current_quote,'Changed');assert.equal(next.groups[0].name,'Changed group');assert.equal(next.calendars[0].color,'#abcdef');assert.equal(next.series[0].id,'series');assert.deepEqual(next.blocks.map(row=>row.id),['new'])})

test('a multi-revision pull applies the final materialized event and note once',()=>{const base=snapshot(),final={...base.blocks[0],title:'Third edit'};const next=applyDatabaseDelta(base,delta(4,12,{upsert_blocks:[final],upsert_block_notes:[{id:'block',content:'Final details'}]}));assert.equal(next.revision,12);assert.equal(next.blocks.length,1);assert.equal(next.blocks[0].title,'Third edit');assert.equal(next.blockNotes[0].content,'Final details')})

test('delta parsing rejects gaps, backwards cursors, and incomplete patches',()=>{assert.throws(()=>parseDatabaseDelta(delta(5,6),4),/Invalid workspace delta/);assert.throws(()=>parseDatabaseDelta(delta(4,3),4),/Invalid workspace delta/);const incomplete=delta(4,5);delete incomplete.patch.delete_block_ids;assert.throws(()=>parseDatabaseDelta(incomplete,4),/Invalid workspace delta/)})

test('delta application rejects a cursor that does not match the cached checkpoint',()=>{assert.throws(()=>applyDatabaseDelta(snapshot(),delta(3,5)),/cursor mismatch/)})

test('two browsers converge through ordered deltas while preserving disjoint pending work',()=>{const original=snapshot(),browserA=structuredClone(original),browserB=structuredClone(original),aRow={...original.blocks[0],title:'Edited in A'},serverAfterA=applyDatabaseDelta(original,delta(4,5,{upsert_blocks:[aRow]})),bPending=structuredClone(browserB);bPending.blockNotes[0].content='Edited in B';const bRebase=mergeSnapshots(original,bPending,serverAfterA);assert.deepEqual(bRebase.conflicts,[]);assert.equal(bRebase.snapshot.blocks[0].title,'Edited in A');assert.equal(bRebase.snapshot.blockNotes[0].content,'Edited in B');const finalRow=bRebase.snapshot.blocks[0],finalNote=bRebase.snapshot.blockNotes[0],serverAfterB=applyDatabaseDelta(serverAfterA,delta(5,6,{upsert_blocks:[finalRow],upsert_block_notes:[finalNote]})),aConverged=applyDatabaseDelta(browserA,delta(4,6,{upsert_blocks:[finalRow],upsert_block_notes:[finalNote]}));assert.deepEqual(aConverged,serverAfterB)})

test('two browsers do not silently resolve a same-field race',()=>{const base=snapshot(),local=structuredClone(base),remote=applyDatabaseDelta(base,delta(4,5,{upsert_blocks:[{...base.blocks[0],title:'Browser A'}]}));local.blocks[0].title='Browser B';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,['blocks.block.title']);assert.equal(result.snapshot.blocks[0].title,'Browser B')})
