const fs=require('node:fs')
const test=require('node:test')
const assert=require('node:assert/strict')
const ts=require('typescript')

require.extensions['.ts']=(module,filename)=>{const source=fs.readFileSync(filename,'utf8'),output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;module._compile(output,filename)}

const {mergeSnapshots}=require('../lib/supabase/merge.ts')
const {applyDatabaseDelta,parseDatabaseDelta}=require('../lib/supabase/sync.ts')
const {sparseRowChanges}=require('../lib/supabase/rows.ts')

const snapshot=()=>({revision:4,account:{settings:{wakeHour:7,sleepHour:22,snapMinutes:15,defaultDuration:60,hourScale:64,showWeekends:true,timeFormat:'12h',underlayOpacity:40,defaultCategoryId:'work'},quote_bank:['Focus'],current_quote:'Focus'},groups:[{id:'group',name:'Main',position:0}],calendars:[{id:'work',group_id:'group',name:'Work',color:'#123456',is_visible:true,position:0,deleted_at:null}],series:[],blocks:[{id:'block',category_id:'work',date:'2026-07-14',start_minute:540,end_minute:600,title:'Plan',layer:'plan',all_day:false,source_plan_id:null,status:null,series_id:null,occurrence_index:null,recurrence_date:null,recurrence_start_minute:null,recurrence_end_minute:null}],blockNotes:[{id:'block',content:'Plan details'}]})
const patch=(overrides={})=>({account:null,upsert_groups:[],delete_group_ids:[],upsert_calendars:[],delete_calendar_ids:[],upsert_series:[],delete_series_ids:[],upsert_blocks:[],delete_block_ids:[],upsert_block_notes:[],delete_block_note_ids:[],...overrides})
const delta=(from,to,changes={})=>({from_revision:from,to_revision:to,patch:patch(changes)})

test('the shared sparse diff emits only changed fields for an existing note or event',()=>{const before=[{id:'event',title:'Plan',content:'Old note',start:540}],after=[{id:'event',title:'Plan',content:'New note',start:540}],changes=sparseRowChanges(before,after);assert.deepEqual(changes.upserts,[]);assert.deepEqual(changes.updates,[{id:'event',content:'New note'}]);assert.deepEqual(changes.deletes,[])})

test('three-way merge combines independent event and note edits',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks[0].title='Local title';remote.blockNotes[0].content='Remote note';remote.revision=5;const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.revision,5);assert.equal(result.snapshot.blocks[0].title,'Local title');assert.equal(result.snapshot.blockNotes[0].content,'Remote note')})

test('three-way merge reports overlapping edits and keeps local as the proposed resolution',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks[0].title='Local title';remote.blocks[0].title='Remote title';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,['blocks.block.title']);assert.equal(result.snapshot.blocks[0].title,'Local title')})

test('delete versus edit is an explicit conflict',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks=[];remote.blocks[0].title='Remote title';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,['blocks.block']);assert.equal(result.snapshot.blocks.length,0)})

test('independent row changes merge without conflict',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks.push({...local.blocks[0],id:'local',title:'Local block'});remote.groups[0].name='Remote group';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.groups[0].name,'Remote group');assert.equal(result.snapshot.blocks.find(block=>block.id==='local').title,'Local block')})

test('independent settings fields merge without replacing the settings object',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.account.settings.hourScale=72;remote.account.settings.showWeekends=false;const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.account.settings.hourScale,72);assert.equal(result.snapshot.account.settings.showWeekends,false)})

test('object key order does not create false changes or conflicts',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.account.settings=Object.fromEntries(Object.entries(local.account.settings).reverse());remote.groups[0].name='Remote group';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,[]);assert.equal(result.snapshot.groups[0].name,'Remote group')})

test('server conflict choice keeps independent local note edits',()=>{const base=snapshot(),local=structuredClone(base),remote=structuredClone(base);local.blocks[0].title='Local title';local.blockNotes[0].content='Local note';remote.blocks[0].title='Remote title';const result=mergeSnapshots(base,remote,local);assert.deepEqual(result.conflicts,['blocks.block.title']);assert.equal(result.snapshot.blocks[0].title,'Remote title');assert.equal(result.snapshot.blockNotes[0].content,'Local note')})

test('an empty delta advances the durable cursor without replacing cached rows',()=>{const base=snapshot(),next=applyDatabaseDelta(base,delta(4,7));assert.equal(next.revision,7);assert.deepEqual(next.account,base.account);assert.deepEqual(next.blocks,base.blocks);assert.notEqual(next.blocks,base.blocks)})

test('a delta replaces only changed rows and independently replaces only changed notes',()=>{const base=snapshot();base.blocks.push({...base.blocks[0],id:'untouched',title:'Untouched'});base.blockNotes.push({id:'untouched',content:'Cached detail'});const changed={...base.blocks[0],title:'Remote title'};const next=applyDatabaseDelta(base,delta(4,5,{upsert_blocks:[changed],upsert_block_notes:[{id:'block',content:'Remote note'}]}));assert.equal(next.revision,5);assert.equal(next.blocks.find(row=>row.id==='block').title,'Remote title');assert.equal(next.blockNotes.find(row=>row.id==='block').content,'Remote note');assert.equal(next.blockNotes.find(row=>row.id==='untouched').content,'Cached detail')})

test('delete tombstones remove only named rows',()=>{const base=snapshot();base.blocks.push({...base.blocks[0],id:'keep'});const next=applyDatabaseDelta(base,delta(4,6,{delete_block_ids:['block']}));assert.deepEqual(next.blocks.map(row=>row.id),['keep'])})

test('a checkpoint patch can atomically update every entity kind',()=>{const base=snapshot(),account={...base.account,current_quote:'Changed'},group={...base.groups[0],name:'Changed group'},calendar={...base.calendars[0],color:'#abcdef'},series={id:'series',recurrence:{frequency:'weekly',interval:1,weekdays:[2],weeks:2}},block={...base.blocks[0],id:'new',series_id:'series'};const next=applyDatabaseDelta(base,delta(4,8,{account,upsert_groups:[group],upsert_calendars:[calendar],upsert_series:[series],upsert_blocks:[block],delete_block_ids:['block']}));assert.equal(next.revision,8);assert.equal(next.account.current_quote,'Changed');assert.equal(next.groups[0].name,'Changed group');assert.equal(next.calendars[0].color,'#abcdef');assert.equal(next.series[0].id,'series');assert.deepEqual(next.blocks.map(row=>row.id),['new'])})

test('a multi-revision pull applies the final materialized event and note once',()=>{const base=snapshot(),final={...base.blocks[0],title:'Third edit'};const next=applyDatabaseDelta(base,delta(4,12,{upsert_blocks:[final],upsert_block_notes:[{id:'block',content:'Final details'}]}));assert.equal(next.revision,12);assert.equal(next.blocks.length,1);assert.equal(next.blocks[0].title,'Third edit');assert.equal(next.blockNotes[0].content,'Final details')})

test('delta parsing rejects gaps, backwards cursors, and incomplete patches',()=>{assert.throws(()=>parseDatabaseDelta(delta(5,6),4),/Invalid workspace delta/);assert.throws(()=>parseDatabaseDelta(delta(4,3),4),/Invalid workspace delta/);const incomplete=delta(4,5);delete incomplete.patch.delete_block_ids;assert.throws(()=>parseDatabaseDelta(incomplete,4),/Invalid workspace delta/)})

test('delta application rejects a cursor that does not match the cached checkpoint',()=>{assert.throws(()=>applyDatabaseDelta(snapshot(),delta(3,5)),/cursor mismatch/)})

test('two browsers converge through ordered deltas while preserving disjoint pending work',()=>{const original=snapshot(),browserA=structuredClone(original),browserB=structuredClone(original),aRow={...original.blocks[0],title:'Edited in A'},serverAfterA=applyDatabaseDelta(original,delta(4,5,{upsert_blocks:[aRow]})),bPending=structuredClone(browserB);bPending.blockNotes[0].content='Edited in B';const bRebase=mergeSnapshots(original,bPending,serverAfterA);assert.deepEqual(bRebase.conflicts,[]);assert.equal(bRebase.snapshot.blocks[0].title,'Edited in A');assert.equal(bRebase.snapshot.blockNotes[0].content,'Edited in B');const finalRow=bRebase.snapshot.blocks[0],finalNote=bRebase.snapshot.blockNotes[0],serverAfterB=applyDatabaseDelta(serverAfterA,delta(5,6,{upsert_blocks:[finalRow],upsert_block_notes:[finalNote]})),aConverged=applyDatabaseDelta(browserA,delta(4,6,{upsert_blocks:[finalRow],upsert_block_notes:[finalNote]}));assert.deepEqual(aConverged,serverAfterB)})

test('two browsers do not silently resolve a same-field race',()=>{const base=snapshot(),local=structuredClone(base),remote=applyDatabaseDelta(base,delta(4,5,{upsert_blocks:[{...base.blocks[0],title:'Browser A'}]}));local.blocks[0].title='Browser B';const result=mergeSnapshots(base,local,remote);assert.deepEqual(result.conflicts,['blocks.block.title']);assert.equal(result.snapshot.blocks[0].title,'Browser B')})
