const fs=require('node:fs')
const test=require('node:test')
const assert=require('node:assert/strict')
const ts=require('typescript')

require.extensions['.ts']=(module,filename)=>{const source=fs.readFileSync(filename,'utf8'),output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;module._compile(output,filename)}

const {linkedAllocatedMinutes,recurringScopeIds,resolveTodoLinkClick,shouldEndShiftLinking,visibleTodoTabs}=require('../lib/calendar/todo.ts')
const blocks=[
  {id:'a',date:'2026-07-01',start:9,end:10.5,title:'A',categoryId:'work',layer:'plan',seriesId:'series',occurrenceIndex:0},
  {id:'b',date:'2026-07-08',start:9,end:11,title:'B',categoryId:'work',layer:'plan',seriesId:'series',occurrenceIndex:1},
  {id:'c',date:'2026-07-15',start:9,end:10,title:'C',categoryId:'work',layer:'plan',seriesId:'series',occurrenceIndex:2},
  {id:'all-day',date:'2026-07-15',start:0,end:24,title:'Day',categoryId:'work',layer:'plan',allDay:true},
]

test('to-do allocation sums linked timed events and ignores all-day placeholders',()=>{assert.equal(linkedAllocatedMinutes(blocks,['a','b','all-day']),210)})
test('recurring to-do links use the same only, following, and all scopes as event edits',()=>{assert.deepEqual(recurringScopeIds(blocks,blocks[1],'only'),['b']);assert.deepEqual(recurringScopeIds(blocks,blocks[1],'following'),['b','c']);assert.deepEqual(recurringScopeIds(blocks,blocks[1],'all'),['a','b','c'])})
test('Shift linking records handled clicks independently of whether the event was newly linked',()=>{const linked=['a'],existing=resolveTodoLinkClick('task',linked,'a',true),added=resolveTodoLinkClick('task',linked,'b',true),normalExisting=resolveTodoLinkClick('task',linked,'a',false),normalAdded=resolveTodoLinkClick('task',linked,'b',false);assert.deepEqual(existing,{alreadyLinked:true,nextLinkedBlockIds:linked,shiftClickedTodoId:'task',closeImmediately:false});assert.deepEqual(added,{alreadyLinked:false,nextLinkedBlockIds:['a','b'],shiftClickedTodoId:'task',closeImmediately:false});assert.deepEqual(normalExisting,{alreadyLinked:true,nextLinkedBlockIds:linked,shiftClickedTodoId:null,closeImmediately:true});assert.deepEqual(normalAdded,{alreadyLinked:false,nextLinkedBlockIds:['a','b'],shiftClickedTodoId:null,closeImmediately:true});assert.deepEqual(linked,['a'])})
test('Shift linking ends only after this task handled a click and Shift is no longer held',()=>{assert.equal(shouldEndShiftLinking(null,'task',false),false);assert.equal(shouldEndShiftLinking('other','task',false),false);assert.equal(shouldEndShiftLinking('task','task',true),false);assert.equal(shouldEndShiftLinking('task','task',false),true)})
test('to-do filters keep empty and favorite tabs while hiding non-matching ordinary tabs',()=>{const tabs=[{id:'empty',name:'Empty'},{id:'open',name:'Open'},{id:'done',name:'Done'},{id:'mixed',name:'Mixed'},{id:'favorite',name:'Favorite',favorite:true}],items=[{id:'open-item',tabId:'open',title:'Open'},{id:'done-item',tabId:'done',title:'Done',completed:true},{id:'mixed-open',tabId:'mixed',title:'Open'},{id:'mixed-done',tabId:'mixed',title:'Done',completed:true},{id:'favorite-done',tabId:'favorite',title:'Done',completed:true}];assert.deepEqual(visibleTodoTabs(tabs,items,'all').map(tab=>tab.id),['empty','open','done','mixed','favorite']);assert.deepEqual(visibleTodoTabs(tabs,items,'open').map(tab=>tab.id),['empty','open','mixed','favorite']);assert.deepEqual(visibleTodoTabs(tabs,items,'done').map(tab=>tab.id),['empty','done','mixed','favorite'])})
test('weekly insights remains the fallback and the to-do header button toggles a closable panel',()=>{const app=fs.readFileSync(require.resolve('../components/calendar/CalendarApp.tsx'),'utf8'),header=fs.readFileSync(require.resolve('../components/calendar/AppHeader.tsx'),'utf8');assert.ok(app.includes("utilityPanel&&utilityPanel!=='insights'?utilityPanel:'insights'"));assert.ok(header.includes("p.panel==='todos'?null:'todos'"))})
test('task and list names edit inline without a duplicate drag overlay',()=>{const panel=fs.readFileSync(require.resolve('../components/calendar/TodoPanel.tsx'),'utf8'),css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8');assert.ok(panel.includes('<input className="todo-title"'));assert.ok(!panel.includes('todo-title-input'));assert.ok(!panel.includes('setExpandedIds(current=>new Set(current).add'));assert.ok(!panel.includes('DragOverlay')&&!panel.includes('activeId'));assert.ok(!css.includes('.todo-drag-overlay'));assert.ok(panel.includes('onBlur={commitTitle} onKeyDown={e=>{e.stopPropagation()'));assert.ok(panel.includes('onBlur={commit} onKeyDown={e=>{e.stopPropagation()'))})
test('task rows use one neutral hover delete and favorite tabs stay muted and hover-only without bypassing item filters',()=>{const panel=fs.readFileSync(require.resolve('../components/calendar/TodoPanel.tsx'),'utf8'),app=fs.readFileSync(require.resolve('../components/calendar/CalendarApp.tsx'),'utf8'),store=fs.readFileSync(require.resolve('../hooks/useCalendarStore.ts'),'utf8'),css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8');assert.ok(panel.includes('className="todo-item-delete"'));assert.ok(!panel.includes('className="todo-delete"'));assert.ok(!panel.includes('title="Delete task"'));assert.ok(!panel.includes('title="Delete list; tasks move to the first list"'));assert.match(panel,/className=\{`todo-tab-favorite[^>]+title=\{tab\.favorite\?/);assert.ok(panel.includes("<Star size={10} fill={tab.favorite?'currentColor':'none'}/>"));assert.ok(panel.includes('items={shown.filter(item=>item.tabId===tab.id&&matchesFilter(item))}'));assert.ok(app.includes('onToggleFavoriteTab={store.toggleTodoTabFavorite}'));assert.ok(store.includes('const toggleTodoTabFavorite = useCallback'));assert.ok(css.includes('.todo-summary:hover .todo-item-delete'));assert.match(css,/\.todo-item-delete\{[^}]*color:#66686d/);assert.match(css,/\.todo-item-delete:hover\{[^}]*color:var\(--text-2\)/);assert.ok(!css.includes('.todo-link-row>.todo-delete'));assert.ok(css.includes('.todo-tab-favorite+.todo-tab-delete{margin-left:-2px}'));assert.ok(!css.includes('.todo-tab-head:hover .todo-tab-favorite.active{color:#fff}'));assert.ok(!css.includes('.todo-tab-favorite.active{opacity:1'))})
test('checked tasks use the shared accent instead of a green status color',()=>{const css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8');assert.ok(css.includes('.todo-check.todo-check[aria-pressed=true]{border-color:var(--accent);background:var(--accent);color:var(--bg)}'));assert.ok(!css.includes('border-color:#729485;background:#8fb9a7'))})
test('right-edge todo chevrons share the sortable drag surface and completed titles remain muted without a strike',()=>{const panel=fs.readFileSync(require.resolve('../components/calendar/TodoPanel.tsx'),'utf8'),css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8'),tabSection=panel.slice(panel.indexOf('function TodoTabSection'),panel.indexOf('export function TodoPanel'));assert.match(panel,/className="todo-expand"[^>]*onClick=\{onExpand\}/);assert.doesNotMatch(panel,/className="todo-expand"[^>]*onPointerDown/);assert.match(panel,/className="todo-tab-toggle"[^>]*onClick=\{onToggle\}/);assert.doesNotMatch(panel,/className="todo-tab-toggle"[^>]*onPointerDown/);assert.ok(tabSection.indexOf('className="todo-tab-toggle"')>tabSection.indexOf('Add task to'));assert.ok(panel.includes('activationConstraint:{distance:6}'));assert.ok(css.includes('.todo-item.completed .todo-title{color:#65676c}'));assert.ok(!css.includes('.todo-item.completed .todo-title{text-decoration:line-through'))})
test('the todo panel title edits inline and persists only as a device-local panel preference',()=>{const panel=fs.readFileSync(require.resolve('../components/calendar/TodoPanel.tsx'),'utf8'),css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8');assert.ok(panel.includes('function TodoPanelTitle()'));assert.ok(panel.includes("localStorage.getItem('tempo-todo-panel-title')"));assert.ok(panel.includes("localStorage.setItem('tempo-todo-panel-title',next)"));assert.ok(panel.includes('aria-label="To-do panel title"'));assert.ok(panel.includes('<ListTodo size={15}/><TodoPanelTitle/>'));assert.ok(css.includes('.todo-panel-title{min-width:0;width:100%;border:0!important;background:transparent!important;outline:0;padding:0;font:inherit;color:inherit;text-overflow:ellipsis}'))})
test('to-do filtering defaults to unchecked and time summaries omit absent sides cleanly',()=>{const panel=fs.readFileSync(require.resolve('../components/calendar/TodoPanel.tsx'),'utf8');assert.ok(panel.includes("useState<'all'|'open'|'done'>('open')"));assert.ok(panel.includes('view-switch todo-filter-switch'));assert.ok(!panel.includes('Untitled task'));assert.ok(panel.includes('className="todo-link-count"'));assert.ok(!panel.includes('FileText'));assert.ok(!panel.includes('—'));assert.ok(panel.includes("const visibleBlank='\\u00a0'"));assert.ok(panel.includes("linkedCount>0?`${hoursLabel(allocated)} / ${expected==null?visibleBlank:hoursLabel(expected)}`:expected==null?'':hoursLabel(expected)"));assert.ok(panel.includes('todoHoursSummary(linked.size,allocated,item.expectedMinutes)'))})
test('calendar link mode records every Shift-click before duplicate handling and reads Shift when pointer-up completes the click',()=>{const app=fs.readFileSync(require.resolve('../components/calendar/CalendarApp.tsx'),'utf8'),week=fs.readFileSync(require.resolve('../components/calendar/WeekGrid.tsx'),'utf8'),month=fs.readFileSync(require.resolve('../components/calendar/MonthView.tsx'),'utf8'),panel=fs.readFileSync(require.resolve('../components/calendar/TodoPanel.tsx'),'utf8'),css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8'),record=app.indexOf('shiftClickedTodoRef.current=click.shiftClickedTodoId'),duplicate=app.indexOf('if(click.alreadyLinked)');assert.ok(record>=0&&duplicate>record);assert.ok(app.includes('if(click.alreadyLinked){if(click.closeImmediately)setLinkingTodoId(null);return true}const commitId=store.setTodoBlockLinks'));assert.ok(!app.includes("beforeLinks.includes(block.id)?'unlink':'link'"));assert.ok(app.includes('linking={!!linkingTodoId}'));assert.ok(app.includes('shouldEndShiftLinking(shiftClickedTodoRef.current,todoId,event.shiftKey)'));assert.ok(app.includes("window.addEventListener('keyup',stopIfShiftEnded,true)"));assert.ok(app.includes("window.addEventListener('pointermove',stopIfShiftEnded,true)"));assert.ok(week.includes('openOnRelease:linking||!e.shiftKey'));assert.ok(week.includes('openInLinkMode:linking'));assert.ok(week.includes('onOpen(interaction.block.id,interaction.openInLinkMode&&e.shiftKey)'));assert.ok(!week.includes('openKeepLinking'));assert.ok(week.includes('onSelect={linking?undefined:'));assert.ok(month.includes('onOpen(block.id,e.shiftKey)'));assert.ok(panel.includes('Shift-click to select multiple'));assert.match(css,/\.todo-link-mode\{position:absolute;[^}]*bottom:6px/);assert.ok(css.includes('--edit-box-bg'));assert.ok(!css.includes('order:-1'))})
test('ending Shift linking clears the stale trigger focus while preserving normal keyboard focus styling',()=>{const app=fs.readFileSync(require.resolve('../components/calendar/CalendarApp.tsx'),'utf8'),css=fs.readFileSync(require.resolve('../app/globals.css'),'utf8'),blur=app.indexOf('blurLinkTrigger();setLinkingTodoId');assert.ok(blur>=0);assert.ok(app.includes("active instanceof HTMLButtonElement&&active.closest('.todo-link-row')"));assert.ok(css.includes('.todo-link-row>button{height:24px;border:1px solid #303236'));assert.ok(css.includes('html[data-theme=light] .todo-link-row>button{border-color:#d2d8dc'));assert.ok(css.includes('.todo-link-row>button.active{background:var(--accent-dark);color:var(--accent-light)}'));assert.ok(!css.includes('.todo-link-row>button.active{border-color:var(--accent-border)'));assert.ok(css.includes('.todo-link-row>button.active:focus-visible{outline:0}'));assert.ok(!css.includes('.todo-link-row>button:focus-visible{outline:0}'))})
