'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import { loadDemoCalendar, normalizeCalendarData } from '@/lib/calendar/seed'
import type { CalendarBlock, CalendarData, CalendarSettings, Layer } from '@/lib/calendar/types'
import type { RecurrenceRule, RecurrenceScope } from '@/lib/calendar/types'
import { applyScopedUpdate, createSeries, removeScoped } from '@/lib/calendar/recurrence'
import { applyPatch, diffSnapshots, fetchSnapshot, fromDatabaseSnapshot, patchIsEmpty, seedUserNames, toDatabaseSnapshot, type DatabaseSnapshot } from '@/lib/supabase/database'
import { getSupabase } from '@/lib/supabase/client'

const STORAGE_KEY='tempo-calendar-v2'
const HISTORY_LIMIT=50
export type SyncStatus='loading'|'synced'|'pending'|'offline'|'error'|'quota'

const readCalendar=(key:string)=>{try{const raw=localStorage.getItem(key);if(!raw)return null;const parsed=JSON.parse(raw);return parsed.version===2?normalizeCalendarData(parsed):null}catch{return null}}

export function useCalendarStore(user:User) {
  const [data,setData]=useState<CalendarData>(()=>loadDemoCalendar())
  const dataRef=useRef(data)
  const [ready,setReady]=useState(false)
  const [syncStatus,setSyncStatus]=useState<SyncStatus>('loading')
  const [past,setPast]=useState<CalendarData[]>([])
  const [future,setFuture]=useState<CalendarData[]>([])
  const [undo,setUndo]=useState<{label:string}|null>(null)
  const baseRef=useRef<DatabaseSnapshot|null>(null),initializedRef=useRef(false),dirtyRef=useRef(false),inFlightRef=useRef(false),mutationRef=useRef<{target:CalendarData;id:string}|null>(null),flushTimerRef=useRef<number|null>(null),refreshTimerRef=useRef<number|null>(null),flushRef=useRef<()=>void>(()=>{})
  const keys=useMemo(()=>({cache:`${STORAGE_KEY}:${user.id}`,base:`${STORAGE_KEY}:${user.id}:base`,pending:`${STORAGE_KEY}:${user.id}:pending`,mutation:`${STORAGE_KEY}:${user.id}:mutation`}),[user.id])

  useEffect(()=>{dataRef.current=data},[data])
  const scheduleFlush=useCallback((delay=350)=>{if(flushTimerRef.current!==null)window.clearTimeout(flushTimerRef.current);flushTimerRef.current=window.setTimeout(()=>flushRef.current(),delay)},[])
  const markDirty=useCallback((next:CalendarData)=>{dirtyRef.current=true;if(!inFlightRef.current){mutationRef.current=null;localStorage.removeItem(keys.mutation)}setSyncStatus(navigator.onLine?'pending':'offline');localStorage.setItem(keys.cache,JSON.stringify(next));localStorage.setItem(keys.pending,JSON.stringify(next));if(initializedRef.current)scheduleFlush()},[keys,scheduleFlush])
  const acceptRemote=useCallback((snapshot:DatabaseSnapshot,resetHistory=false)=>{const next=fromDatabaseSnapshot(snapshot);baseRef.current=snapshot;dataRef.current=next;mutationRef.current=null;setData(next);if(resetHistory){setPast([]);setFuture([])}localStorage.setItem(keys.cache,JSON.stringify(next));localStorage.setItem(keys.base,JSON.stringify(next));localStorage.removeItem(keys.pending);localStorage.removeItem(keys.mutation);dirtyRef.current=false;setSyncStatus('synced')},[keys])
  const flush=useCallback(async()=>{if(!initializedRef.current||inFlightRef.current||!dirtyRef.current)return;const target=dataRef.current,targetSnapshot=toDatabaseSnapshot(target),patch=diffSnapshots(baseRef.current,targetSnapshot);if(patchIsEmpty(patch)){baseRef.current=targetSnapshot;mutationRef.current=null;localStorage.setItem(keys.base,JSON.stringify(target));localStorage.removeItem(keys.pending);localStorage.removeItem(keys.mutation);dirtyRef.current=false;setSyncStatus('synced');return}const mutation=mutationRef.current?.target===target?mutationRef.current:{target,id:crypto.randomUUID()};mutationRef.current=mutation;localStorage.setItem(keys.mutation,mutation.id);inFlightRef.current=true;setSyncStatus(navigator.onLine?'pending':'offline');try{await applyPatch(patch,mutation.id);mutationRef.current=null;localStorage.removeItem(keys.mutation);baseRef.current=targetSnapshot;localStorage.setItem(keys.base,JSON.stringify(target));if(dataRef.current!==target){dirtyRef.current=true;scheduleFlush(0)}else{dirtyRef.current=false;localStorage.removeItem(keys.pending);const remote=await fetchSnapshot(user.id);if(remote&&dataRef.current===target)acceptRemote(remote);else setSyncStatus('synced')}}catch(error){dirtyRef.current=true;const message=typeof error==='object'&&error&&'message' in error?String(error.message):String(error);setSyncStatus(!navigator.onLine?'offline':message.toLowerCase().includes('storage quota exceeded')?'quota':'error')}finally{inFlightRef.current=false;if(dirtyRef.current&&dataRef.current!==target)scheduleFlush(0)}},[acceptRemote,keys,scheduleFlush,user.id])
  flushRef.current=flush
  useEffect(()=>{let active=true;initializedRef.current=false;dirtyRef.current=false;setReady(false);setSyncStatus('loading');const pending=readCalendar(keys.pending),userCache=readCalendar(keys.cache),cached=pending??userCache??readCalendar(STORAGE_KEY),local=seedUserNames(cached??loadDemoCalendar(),user),storedBase=readCalendar(keys.base),storedMutation=pending?localStorage.getItem(keys.mutation):null;baseRef.current=storedBase?toDatabaseSnapshot(storedBase):null;mutationRef.current=storedMutation?{target:local,id:storedMutation}:null;dataRef.current=local;setData(local);setReady(Boolean(pending||userCache));dirtyRef.current=Boolean(pending);localStorage.setItem(keys.cache,JSON.stringify(local));void fetchSnapshot(user.id).then(remote=>{if(!active)return;if(!remote){baseRef.current=null;dirtyRef.current=true;localStorage.setItem(keys.pending,JSON.stringify(dataRef.current))}else if(!dirtyRef.current)acceptRemote(remote,true);else if(!baseRef.current)baseRef.current=remote;initializedRef.current=true;setReady(true);if(dirtyRef.current)scheduleFlush(0)}).catch(()=>{if(!active)return;initializedRef.current=true;setReady(true);setSyncStatus(navigator.onLine?'error':'offline');if(dirtyRef.current)scheduleFlush(1000)});return()=>{active=false;initializedRef.current=false;if(flushTimerRef.current!==null)window.clearTimeout(flushTimerRef.current)}},[acceptRemote,keys,scheduleFlush,user.id])
  useEffect(()=>{const refresh=()=>{if(dirtyRef.current||inFlightRef.current){scheduleFlush(0);return}void fetchSnapshot(user.id).then(remote=>{if(remote)acceptRemote(remote,true)}).catch(()=>setSyncStatus(navigator.onLine?'error':'offline'))},online=()=>{setSyncStatus(dirtyRef.current?'pending':'synced');dirtyRef.current?scheduleFlush(0):refresh()},visibility=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('online',online);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',visibility);const channel=getSupabase().channel(`user:${user.id}`,{config:{private:true}}).on('broadcast',{event:'*'},()=>{if(refreshTimerRef.current!==null)window.clearTimeout(refreshTimerRef.current);refreshTimerRef.current=window.setTimeout(refresh,180)}).subscribe();return()=>{window.removeEventListener('online',online);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',visibility);if(refreshTimerRef.current!==null)window.clearTimeout(refreshTimerRef.current);void getSupabase().removeChannel(channel)}},[acceptRemote,scheduleFlush,user.id])

  const commit=useCallback((change:(current:CalendarData)=>CalendarData)=>{
    setData(current=>{setPast(items=>[...items.slice(-(HISTORY_LIMIT-1)),structuredClone(current)]);setFuture([]);const next=change(current);dataRef.current=next;markDirty(next);return next})
  },[markDirty])
  const undoHistory=useCallback(()=>{setPast(items=>{if(!items.length)return items;const previous=items[items.length-1];setFuture(next=>[structuredClone(dataRef.current),...next].slice(0,HISTORY_LIMIT));dataRef.current=previous;markDirty(previous);setData(previous);return items.slice(0,-1)})},[markDirty])
  const redoHistory=useCallback(()=>{setFuture(items=>{if(!items.length)return items;const next=items[0];setPast(previous=>[...previous,structuredClone(dataRef.current)].slice(-HISTORY_LIMIT));dataRef.current=next;markDirty(next);setData(next);return items.slice(1)})},[markDirty])

  const addBlock=useCallback((block:CalendarBlock)=>commit(v=>({...v,blocks:[...v.blocks,block]})),[commit])
  const addBlocks=useCallback((blocks:CalendarBlock[])=>commit(v=>({...v,blocks:[...v.blocks,...blocks]})),[commit])
  const createBlock=useCallback((block:Omit<CalendarBlock,'id'>)=>{const created={...block,id:crypto.randomUUID()};addBlock(created);return created},[addBlock])
  const updateBlock=useCallback((block:CalendarBlock)=>commit(v=>({...v,blocks:v.blocks.map(b=>b.id===block.id?block:b)})),[commit])
  const updateRecurringBlock=useCallback((original:CalendarBlock,block:CalendarBlock,scope:RecurrenceScope)=>commit(v=>({...v,blocks:applyScopedUpdate(v.blocks,original,block,scope)})),[commit])
  const updateBlocks=useCallback((changes:CalendarBlock[])=>{const map=new Map(changes.map(b=>[b.id,b]));commit(v=>({...v,blocks:v.blocks.map(b=>map.get(b.id)??b)}))},[commit])
  const deleteBlocks=useCallback((ids:string[])=>{commit(v=>({...v,blocks:v.blocks.filter(b=>!ids.includes(b.id))}));setUndo({label:`Deleted ${ids.length===1?'block':`${ids.length} blocks`}`})},[commit])
  const deleteRecurringBlock=useCallback((block:CalendarBlock,scope:RecurrenceScope)=>{commit(v=>({...v,blocks:removeScoped(v.blocks,block,scope)}));setUndo({label:scope==='only'?'Deleted event':scope==='following'?'Deleted this and following events':'Deleted recurring series'})},[commit])
  const setBlockRecurrence=useCallback((block:CalendarBlock,rule:RecurrenceRule|null)=>commit(v=>{const current=v.blocks.find(b=>b.id===block.id)??block;if(!rule){if(!current.seriesId)return v;return {...v,blocks:v.blocks.map(b=>b.id===current.id?{...b,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined}:b)};}const members=current.seriesId?v.blocks.filter(b=>b.seriesId===current.seriesId):[],root=members.sort((a,b)=>(a.occurrenceIndex??0)-(b.occurrenceIndex??0))[0]??current,withoutSeries=current.seriesId?v.blocks.filter(b=>b.seriesId!==current.seriesId):v.blocks.filter(b=>b.id!==current.id);return {...v,blocks:[...withoutSeries,...createSeries({...root,date:root.recurrenceDate??root.date,start:root.start,end:root.end,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined},rule)]}}),[commit])
  const patchSettings=useCallback((patch:Partial<CalendarSettings>)=>commit(v=>({...v,settings:{...v.settings,...patch}})),[commit])
  const toggleCategory=useCallback((id:string)=>commit(v=>({...v,categories:v.categories.map(c=>c.id===id?{...c,visible:!c.visible}:c)})),[commit])
  const toggleGroup=useCallback((groupId:string)=>commit(v=>{const members=v.categories.filter(c=>c.groupId===groupId),show=members.some(c=>!c.visible);return {...v,categories:v.categories.map(c=>c.groupId===groupId?{...c,visible:show}:c)}}),[commit])
  const reorderCategories=useCallback((sourceId:string,targetId:string)=>commit(v=>{const items=[...v.categories],from=items.findIndex(c=>c.id===sourceId),to=items.findIndex(c=>c.id===targetId);if(from<0||to<0)return v;const targetGroup=items[to].groupId;const [moved]=items.splice(from,1);items.splice(to,0,{...moved,groupId:targetGroup});return {...v,categories:items}}),[commit])
  const moveCategoryToGroup=useCallback((sourceId:string,groupId:string)=>commit(v=>{const source=v.categories.find(c=>c.id===sourceId);if(!source||source.groupId===groupId)return v;return {...v,categories:[...v.categories.filter(c=>c.id!==sourceId),{...source,groupId}]}}),[commit])
  const applyCategoryLayout=useCallback((layout:{id:string;groupId?:string}[])=>commit(v=>{const byId=new Map(v.categories.map(c=>[c.id,c]));return {...v,categories:layout.map(item=>({...byId.get(item.id)!,groupId:item.groupId}))}}),[commit])
  const reorderGroups=useCallback((sourceId:string,targetId:string)=>commit(v=>{const items=[...v.groups],from=items.findIndex(g=>g.id===sourceId),to=items.findIndex(g=>g.id===targetId);if(from<0||to<0)return v;const [moved]=items.splice(from,1);items.splice(to,0,moved);return {...v,groups:items}}),[commit])
  const renameGroup=useCallback((id:string,name:string)=>commit(v=>({...v,groups:v.groups.map(g=>g.id===id?{...g,name}:g)})),[commit])
  const createGroup=useCallback(()=>{const group={id:crypto.randomUUID(),name:'New tab'};commit(v=>({...v,groups:[...v.groups,group]}));return group},[commit])
  const renameCategory=useCallback((id:string,name:string)=>commit(v=>({...v,categories:v.categories.map(c=>c.id===id?{...c,name}:c)})),[commit])
  const createCategory=useCallback(()=>{const category={id:crypto.randomUUID(),name:'New calendar',color:'#7da3e8',visible:true,groupId:dataRef.current.groups[0]?.id};commit(v=>({...v,categories:[...v.categories,category]}));return category},[commit])
  const colorCategory=useCallback((id:string,color:string)=>commit(v=>({...v,categories:v.categories.map(c=>c.id===id?{...c,color}:c)})),[commit])
  const setDefaultCategory=useCallback((id:string)=>patchSettings({defaultCategoryId:id}),[patchSettings])
  const deleteCategory=useCallback((id:string)=>commit(v=>{if(v.categories.length<=1)return v;const category=v.categories.find(c=>c.id===id);if(!category)return v;const removedBlocks=v.blocks.filter(b=>b.categoryId===id),remaining=v.categories.filter(c=>c.id!==id),fallback=remaining[0]?.id??'';return {...v,categories:remaining,blocks:v.blocks.filter(b=>b.categoryId!==id),deletedCalendars:[{category,blocks:removedBlocks,deletedAt:new Date().toISOString()},...(v.deletedCalendars??[])],settings:{...v.settings,defaultCategoryId:v.settings.defaultCategoryId===id?fallback:v.settings.defaultCategoryId}}}),[commit])
  const restoreCategory=useCallback((id:string)=>commit(v=>{const entry=(v.deletedCalendars??[]).find(item=>item.category.id===id);if(!entry)return v;return {...v,categories:[...v.categories,{...entry.category,visible:true}],blocks:[...v.blocks,...entry.blocks],deletedCalendars:(v.deletedCalendars??[]).filter(item=>item.category.id!==id)}}),[commit])
  const mergeCategory=useCallback((sourceId:string,targetId:string)=>commit(v=>({...v,categories:v.categories.filter(c=>c.id!==sourceId),blocks:v.blocks.map(b=>b.categoryId===sourceId?{...b,categoryId:targetId}:b),settings:{...v.settings,defaultCategoryId:v.settings.defaultCategoryId===sourceId?targetId:v.settings.defaultCategoryId}})),[commit])
  const setQuote=useCallback((quote:string)=>commit(v=>({...v,currentQuote:quote})),[commit])
  const nextQuote=useCallback(()=>commit(v=>{const choices=v.quoteBank.filter(q=>q!==v.currentQuote),next=choices[Math.floor(Math.random()*choices.length)]??v.currentQuote;return {...v,currentQuote:next}}),[commit])
  const copyPlanToActual=useCallback((dates:string[])=>{const current=dataRef.current,actuals=current.blocks.filter(b=>b.layer==='actual'),existing=new Set(actuals.filter(b=>b.sourcePlanId).map(b=>b.sourcePlanId)),natural=new Set(actuals.map(b=>`${b.date}|${b.title.toLocaleLowerCase()}`));const copies=current.blocks.filter(b=>b.layer==='plan'&&dates.includes(b.date)&&!existing.has(b.id)&&!natural.has(`${b.date}|${b.title.toLocaleLowerCase()}`)).map(b=>({...b,id:crypto.randomUUID(),layer:'actual' as Layer,sourcePlanId:b.id,status:'completed' as const,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined}));if(copies.length)commit(v=>({...v,blocks:[...v.blocks,...copies]}));return copies.length},[commit])
  const reset=useCallback(()=>commit(()=>loadDemoCalendar()),[commit])
  const replaceData=useCallback((next:CalendarData)=>{if(next.version!==2||!Array.isArray(next.blocks)||!Array.isArray(next.categories))throw new Error('Unsupported calendar file');commit(()=>normalizeCalendarData(next))},[commit])
  const undoDelete=useCallback(()=>{undoHistory();setUndo(null)},[undoHistory])

  return useMemo(()=>({data,ready,syncStatus,undo,setUndo,canUndo:past.length>0,canRedo:future.length>0,undoHistory,redoHistory,undoDelete,addBlock,addBlocks,createBlock,updateBlock,updateRecurringBlock,updateBlocks,deleteBlocks,deleteRecurringBlock,setBlockRecurrence,patchSettings,toggleCategory,toggleGroup,reorderCategories,moveCategoryToGroup,applyCategoryLayout,reorderGroups,renameGroup,createGroup,renameCategory,createCategory,colorCategory,setDefaultCategory,deleteCategory,restoreCategory,mergeCategory,setQuote,nextQuote,copyPlanToActual,reset,replaceData}),[data,ready,syncStatus,undo,past.length,future.length,undoHistory,redoHistory,undoDelete,addBlock,addBlocks,createBlock,updateBlock,updateRecurringBlock,updateBlocks,deleteBlocks,deleteRecurringBlock,setBlockRecurrence,patchSettings,toggleCategory,toggleGroup,reorderCategories,moveCategoryToGroup,applyCategoryLayout,reorderGroups,renameGroup,createGroup,renameCategory,createCategory,colorCategory,setDefaultCategory,deleteCategory,restoreCategory,mergeCategory,setQuote,nextQuote,copyPlanToActual,reset,replaceData])
}
