'use client'
import { Check, ChevronDown } from 'lucide-react'
import { useRef, useState } from 'react'
import { useAnchoredMenuPosition, useDismiss } from './FloatingMenuCore'

export type CalendarDropdownOption<T extends string|number>={value:T;label:string;disabled?:boolean}
type Props<T extends string|number>={value:T;options:readonly CalendarDropdownOption<T>[];onChange:(value:T)=>void;ariaLabel:string;compact?:boolean;className?:string}

export function CalendarDropdown<T extends string|number>({value,options,onChange,ariaLabel,compact=false,className=''}:Props<T>){const[open,setOpen]=useState(false),buttonRef=useRef<HTMLButtonElement>(null),popoverRef=useRef<HTMLDivElement>(null),optionRefs=useRef<(HTMLButtonElement|null)[]>([]),ref=useDismiss(reason=>{setOpen(false);if(reason==='escape')requestAnimationFrame(()=>buttonRef.current?.focus())},open),popStyle=useAnchoredMenuPosition(buttonRef,popoverRef,open,{width:'anchor'}),selectedIndex=Math.max(0,options.findIndex(option=>option.value===value)),selected=options[selectedIndex],focusOption=(index:number)=>requestAnimationFrame(()=>optionRefs.current[index]?.focus()),openMenu=(index=selectedIndex)=>{setOpen(true);focusOption(index)},close=()=>{setOpen(false);requestAnimationFrame(()=>buttonRef.current?.focus())},choose=(option:CalendarDropdownOption<T>)=>{if(option.disabled)return;onChange(option.value);close()},move=(index:number,delta:number)=>{let next=index;do next=(next+delta+options.length)%options.length;while(options[next]?.disabled&&next!==index);optionRefs.current[next]?.focus()};return <div className={`calendar-dropdown${compact?' compact':''}${className?` ${className}`:''}`} ref={ref}><button ref={buttonRef} type="button" className="calendar-dropdown-trigger" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} onClick={()=>open?setOpen(false):openMenu()} onKeyDown={event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();openMenu(event.key==='ArrowDown'?selectedIndex:Math.max(0,options.length-1))}}}><span>{selected?.label}</span><ChevronDown size={12}/></button>{open&&<div ref={popoverRef} className="calendar-dropdown-popover" role="listbox" aria-label={ariaLabel} style={popStyle}>{options.map((option,index)=><button ref={node=>{optionRefs.current[index]=node}} key={String(option.value)} type="button" role="option" aria-selected={option.value===value} disabled={option.disabled} onClick={()=>choose(option)} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();close()}else if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();move(index,event.key==='ArrowDown'?1:-1)}else if(event.key==='Home'||event.key==='End'){event.preventDefault();const next=event.key==='Home'?options.findIndex(item=>!item.disabled):options.findLastIndex(item=>!item.disabled);if(next>=0)optionRefs.current[next]?.focus()}}}><span>{option.label}</span>{option.value===value&&<Check size={11}/>}</button>)}</div>}</div>}
