'use client'
import { useLayoutEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

export type TipLine={text:string;hi?:boolean;mid?:string;right?:string;color?:string}
export type TipData={title?:string;timeRight?:string;color?:string;lines:TipLine[]}
type Tip=TipData&{cx:number;anchorTop:number;anchorBottom:number}
type TipPos={cx:number;top:number;arrowPct:number;below:boolean}

export function useCalendarTooltip(boundaryRef?:React.RefObject<HTMLElement|null>){const[tip,setTip]=useState<Tip|null>(null),[tipPos,setTipPos]=useState<TipPos|null>(null),tipRef=useRef<HTMLDivElement|null>(null),hideTimer=useRef<ReturnType<typeof setTimeout>|null>(null);useLayoutEffect(()=>{if(!tip||!tipRef.current){setTipPos(null);return}const w=tipRef.current.offsetWidth,h=tipRef.current.offsetHeight,rightBound=boundaryRef?.current?.getBoundingClientRect().right??window.innerWidth,cx=Math.min(rightBound-w/2-8,Math.max(w/2+8,tip.cx)),arrowPct=Math.min(92,Math.max(8,(tip.cx-cx+w/2)/w*100)),spaceBelow=window.innerHeight-(tip.anchorBottom+10),below=spaceBelow>=h+4,top=below?tip.anchorBottom+10:tip.anchorTop-10;setTipPos({cx,top,arrowPct,below})},[boundaryRef,tip]);const makeTip=(rect:{left:number;top:number;bottom:number;width:number},data:TipData)=>{if(hideTimer.current)clearTimeout(hideTimer.current);setTipPos(null);setTip({...data,cx:rect.left+rect.width/2,anchorTop:rect.top,anchorBottom:rect.bottom})},showTip=(e:React.SyntheticEvent<Element>,data:TipData)=>makeTip(e.currentTarget.getBoundingClientRect(),data),hideTip=()=>{hideTimer.current=setTimeout(()=>setTip(null),500)},cancelHide=()=>{if(hideTimer.current)clearTimeout(hideTimer.current)};return{makeTip,showTip,hideTip,tooltip:tip&&createPortal(<div ref={tipRef} className={`insights-tip ${(tipPos?.below??true)?'tip-below':'tip-above'}${tipPos?'':' tip-placing'}`} style={{left:tipPos?.cx??tip.cx,top:tipPos?.top??(tip.anchorBottom+10),'--tip-color':tip.color??'#e0e1e3','--arrow-x':`${tipPos?.arrowPct??50}%`} as React.CSSProperties} onMouseEnter={cancelHide} onMouseLeave={hideTip}>{tip.title&&<div className="tip-head"><b>{tip.title}</b>{tip.timeRight&&<span className="tip-right">{tip.timeRight}</span>}</div>}{tip.lines.map((line,i)=><span key={i} className="tip-line" style={line.color?{'--tip-line-color':line.color} as React.CSSProperties:undefined}><span className="tip-left"><span className={line.hi?'tip-hi':''}>{line.text}</span>{line.mid&&<span className="tip-mid"> {line.mid}</span>}</span>{line.right&&<span className="tip-lr">{line.right}</span>}</span>)}</div>,document.body)}}
