'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import { AlertTriangle, BarChart3, CalendarDays, Check, Search, Settings2, Target } from 'lucide-react'
import { useCalendarStore } from '@/hooks/useCalendarStore'
import { addDays, rangeLabel, toISO, weekDates } from '@/lib/calendar/date'
import { toTitleCase } from '@/lib/calendar/title-case'
import type { CalendarBlock, Layer, Panel, RecurrenceRule, RecurrenceScope, UtilityPanel, ViewMode } from '@/lib/calendar/types'
import { AppHeader } from './AppHeader'
import { Sidebar } from './Sidebar'
import { WeekGrid } from './WeekGrid'
import { MonthView } from './MonthView'
import { EventInspector } from './EventInspector'
import { InsightsPanel } from './InsightsPanel'
import { SettingsPanel } from './SettingsPanel'
import { SearchPanel } from './SearchPanel'
import { ShortcutsPanel } from './ShortcutsPanel'
import { CommandPalette } from './CommandPalette'
import { EventMenu } from './FloatingMenus'
import { ResizeHandle } from './ResizeHandle'
import { RecurrenceScopeDialog } from './RecurrenceScopeDialog'
import { AppLoading } from '@/components/AppLoading'

export function CalendarApp({user,onSignOut}:{user:User;onSignOut:()=>void}){
  const store=useCalendarStore(user),{data}=store
  const [layer,setLayer]=useState<Layer>('plan'),[view,setView]=useState<ViewMode>('week'),[anchor,setAnchor]=useState(()=>new Date())
  const [utilityPanel,setUtilityPanel]=useState<UtilityPanel>(null),[eventOpen,setEventOpen]=useState(false),[sidebarOpen,setSidebarOpen]=useState(true)
  const [selectedIds,setSelectedIds]=useState<string[]>([]),[draftBlock,setDraftBlock]=useState<CalendarBlock|null>(null),[eventMenu,setEventMenu]=useState<{id:string;x:number;y:number}|null>(null)
  const [commandOpen,setCommandOpen]=useState(false),[toast,setToast]=useState('')
  const [scopeRequest,setScopeRequest]=useState<{action:'edit'|'move'|'resize'|'delete';run:(scope:RecurrenceScope)=>void;cancel?:()=>void}|null>(null)
  const [pendingRecurringEdit,setPendingRecurringEdit]=useState<{original:CalendarBlock;next:CalendarBlock}|null>(null)
  const [leftWidth,setLeftWidth]=useState(232),[rightWidth,setRightWidth]=useState(296)
  const blockClipboard=useRef<CalendarBlock[]>([])
  const editScopeRef=useRef<{id:string;scope:RecurrenceScope}|null>(null)
  const flushPendingEditRef=useRef<(andThen:()=>void)=>void>(andThen=>andThen())
  const dates=useMemo(()=>view==='day'?[anchor]:weekDates(anchor,data.settings.showWeekends),[anchor,view,data.settings.showWeekends])
  const renderedBlocks=useMemo(()=>{const base=pendingRecurringEdit?data.blocks.map(b=>b.id===pendingRecurringEdit.next.id?pendingRecurringEdit.next:b):data.blocks;return draftBlock?[...base,draftBlock]:base},[data.blocks,draftBlock,pendingRecurringEdit])
  const selected=renderedBlocks.find(b=>b.id===selectedIds[selectedIds.length-1])
  const activePanel:Panel=eventOpen&&selected?'event':utilityPanel&&utilityPanel!=='insights'?utilityPanel:'insights'

  const select=useCallback((id:string,additive:boolean)=>setSelectedIds(v=>additive?(v.includes(id)?v.filter(x=>x!==id):[...v,id]):[id]),[])
  const selectMany=useCallback((ids:string[])=>setSelectedIds(ids),[])
  const open=useCallback((id:string)=>{flushPendingEditRef.current(()=>{editScopeRef.current=null;setDraftBlock(current=>current&&current.id!==id?null:current);setSelectedIds([id]);setEventOpen(true);setEventMenu(null)})},[])
  const showUtility=useCallback((next:Panel)=>{if(next==='event')return;editScopeRef.current=null;setUtilityPanel(next);setEventOpen(false);setDraftBlock(null)},[])
  const navigate=useCallback((n:number,oneDay=false)=>setAnchor(v=>addDays(v,n*(oneDay?1:view==='day'?1:view==='week'?7:30))),[view])
  const createDraft=useCallback((input:Omit<CalendarBlock,'id'>)=>{const block={...input,id:crypto.randomUUID()};setDraftBlock(block);return block},[])
  const newBlock=useCallback(()=>{editScopeRef.current=null;const date=view==='month'?anchor:dates[0],block=createDraft({date:toISO(date),start:9,end:9+data.settings.defaultDuration,title:'',categoryId:data.settings.defaultCategoryId,layer});setSelectedIds([block.id]);setEventOpen(true)},[anchor,dates,view,layer,data.settings.defaultCategoryId,data.settings.defaultDuration,createDraft])
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2400)}
  const copyPlan=(targetDates:string[]=dates.map(toISO))=>{const count=store.copyPlanToActual(targetDates);notify(count?`${count} planned ${count===1?'block':'blocks'} copied`:'Actual already matches this plan')}
  const deleteSelected=useCallback(()=>{if(!selectedIds.length)return;if(draftBlock&&selectedIds.includes(draftBlock.id))setDraftBlock(null);const persisted=selectedIds.filter(id=>id!==draftBlock?.id),single=persisted.length===1?data.blocks.find(b=>b.id===persisted[0]):undefined;if(single?.seriesId){setPendingRecurringEdit(null);setScopeRequest({action:'delete',run:scope=>{store.deleteRecurringBlock(single,scope);setSelectedIds([]);setEventOpen(false)}});return}if(persisted.length)store.deleteBlocks(persisted);setSelectedIds([]);setEventOpen(false)},[selectedIds,draftBlock,data.blocks,store])
  const requestBlockChange=useCallback((next:CalendarBlock,action:'edit'|'move'|'resize'='edit')=>{const original=data.blocks.find(b=>b.id===next.id);if(!original?.seriesId){store.updateBlock(next);return}const changed=action==='resize'?original.start!==next.start||original.end!==next.end:action==='move'?original.date!==next.date||original.start!==next.start||original.end!==next.end:original.title!==next.title||original.notes!==next.notes||original.categoryId!==next.categoryId||original.start!==next.start||original.end!==next.end||original.date!==next.date;if(!changed)return;if(action==='edit'){if(original.categoryId!==next.categoryId){const catNext={...original,categoryId:next.categoryId};store.updateRecurringBlock(original,catNext,'all');setPendingRecurringEdit(p=>p&&p.next.id===next.id?{...p,next:{...p.next,categoryId:next.categoryId}}:p);return}const remembered=editScopeRef.current;if(remembered?.id===original.id){store.updateRecurringBlock(original,next,remembered.scope);return}setPendingRecurringEdit(p=>({original:p?.original??original,next}));return}setPendingRecurringEdit(null);setScopeRequest({action,run:scope=>{store.updateRecurringBlock(original,next,scope)}})},[data.blocks,store])
  const changeBlock=useCallback((next:CalendarBlock)=>{if(draftBlock?.id===next.id){if(next.title!==''||next.categoryId!==data.settings.defaultCategoryId){store.addBlock(next);setDraftBlock(null)}else setDraftBlock(next)}else requestBlockChange(next)},[draftBlock,data.settings.defaultCategoryId,requestBlockChange,store])
  const changeRecurrence=useCallback((block:CalendarBlock,rule:RecurrenceRule|null)=>{editScopeRef.current=null;setPendingRecurringEdit(null);if(draftBlock?.id===block.id)setDraftBlock(null);store.setBlockRecurrence(block,rule)},[draftBlock,store])
  const flushPendingEdit=useCallback((andThen:()=>void)=>{if(!pendingRecurringEdit){andThen();return}const{original,next}=pendingRecurringEdit;setScopeRequest({action:'edit',run:scope=>{editScopeRef.current={id:original.id,scope};store.updateRecurringBlock(original,next,scope);setPendingRecurringEdit(null);andThen()},cancel:()=>{setPendingRecurringEdit(null);andThen()}})},[pendingRecurringEdit,store])
  flushPendingEditRef.current=flushPendingEdit
  const closeEvent=()=>{flushPendingEdit(()=>{editScopeRef.current=null;setEventOpen(false);setSelectedIds([]);setDraftBlock(null)})}
  const clearSelection=useCallback(()=>{flushPendingEditRef.current(()=>{editScopeRef.current=null;setSelectedIds([]);setEventOpen(false);setDraftBlock(null)})},[])
  const closeUtility=()=>setUtilityPanel(null)

  const selectedBlocks=useCallback(()=>data.blocks.filter(b=>selectedIds.includes(b.id)),[data.blocks,selectedIds])
  const duplicateSelection=useCallback(()=>{const source=selectedBlocks();if(!source.length)return;const copies=source.map(b=>({...b,id:crypto.randomUUID(),title:b.title?`${b.title} copy`:b.title,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined}));store.addBlocks(copies);setSelectedIds(copies.map(b=>b.id))},[selectedBlocks,store])
  const copySelection=useCallback(()=>{blockClipboard.current=structuredClone(selectedBlocks())},[selectedBlocks])
  const pasteSelection=useCallback(()=>{if(!blockClipboard.current.length)return;const offset=data.settings.snapMinutes/60;const copies=blockClipboard.current.map(b=>{const duration=b.end-b.start,start=Math.min(24-duration,b.start+offset);return {...b,id:crypto.randomUUID(),start,end:start+duration,layer,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined}});store.addBlocks(copies);setSelectedIds(copies.map(b=>b.id));setEventOpen(false)},[data.settings.snapMinutes,layer,store])
  const selectAllOfCalendars=useCallback(()=>{if(!selectedIds.length)return;const catIds=new Set(renderedBlocks.filter(b=>selectedIds.includes(b.id)).map(b=>b.categoryId));setSelectedIds(renderedBlocks.filter(b=>b.layer===layer&&dates.some(d=>toISO(d)===b.date)&&catIds.has(b.categoryId)&&(data.categories.find(c=>c.id===b.categoryId)?.visible??true)).map(b=>b.id))},[selectedIds,renderedBlocks,layer,dates,data.categories])

  useEffect(()=>{if(window.innerWidth<850)setSidebarOpen(false);const left=Number(localStorage.getItem('tempo-left-sidebar-width')),right=Number(localStorage.getItem('tempo-right-sidebar-width'));if(left)setLeftWidth(Math.max(190,Math.min(360,left)));if(right)setRightWidth(Math.max(250,Math.min(440,right)))},[])
  const resizeLeft=(width:number)=>{setLeftWidth(width);localStorage.setItem('tempo-left-sidebar-width',String(Math.round(width)))}
  const resizeRight=(width:number)=>{setRightWidth(width);localStorage.setItem('tempo-right-sidebar-width',String(Math.round(width)))}
  useEffect(()=>{if(!store.undo)return;const timer=window.setTimeout(()=>store.setUndo(null),6000);return()=>window.clearTimeout(timer)},[store.undo,store.setUndo])
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{const key=e.key.toLowerCase(),mod=e.ctrlKey||e.metaKey,target=e.target as HTMLElement,isField=['INPUT','TEXTAREA','SELECT'].includes(target.tagName);if(mod&&key==='d'){e.preventDefault();if(!isField)duplicateSelection();return}if(isField)return;if(mod&&key==='c'){if(selectedIds.length){e.preventDefault();copySelection()}return}if(mod&&key==='v'){if(blockClipboard.current.length){e.preventDefault();pasteSelection()}return}if(mod&&key==='a'){e.preventDefault();if(!isField)selectAllOfCalendars();return}
if(mod&&key==='k'){e.preventDefault();setCommandOpen(true);return}if(mod&&key==='z'){e.preventDefault();e.shiftKey?store.redoHistory():store.undoHistory();return}if(e.key==='?'){showUtility('shortcuts');return}if(e.key==='Escape'){setCommandOpen(false);clearSelection();return}if(e.key==='Delete'||e.key==='Backspace'){deleteSelected();return}if(e.key==='ArrowLeft')navigate(-1,e.shiftKey);if(e.key==='ArrowRight')navigate(1,e.shiftKey);if(key==='n')newBlock();if(key==='t')setAnchor(new Date());if(key==='d')setView('day');if(key==='w')setView('week');if(key==='m')setView('month');if(e.key==='1')setLayer('plan');if(e.key==='2')setLayer('actual');if(key==='i')showUtility('insights');if(e.key==='/'){e.preventDefault();showUtility('search')}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[clearSelection,copySelection,deleteSelected,duplicateSelection,navigate,newBlock,pasteSelection,selectAllOfCalendars,selectedIds.length,showUtility,store])

  const formatAllTitles=()=>{store.updateBlocks(data.blocks.filter(b=>b.title).map(b=>({...b,title:toTitleCase(b.title)})))}
  const duplicate=(source:CalendarBlock)=>{if(source.id===draftBlock?.id)return;store.createBlock({...source,title:`${source.title} copy`,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined})}
  const copyLayer=(source:CalendarBlock,target:Layer)=>{if(source.id===draftBlock?.id)return;store.createBlock({...source,layer:target,sourcePlanId:target==='actual'&&source.layer==='plan'?source.id:undefined,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined})}
  const actions=[{label:'Create new block',hint:'N',icon:<CalendarDays size={15}/>,run:newBlock},{label:'Go to today',hint:'T',icon:<CalendarDays size={15}/>,run:()=>setAnchor(new Date())},{label:'Switch to Plan',hint:'1',icon:<Target size={15}/>,run:()=>setLayer('plan')},{label:'Switch to Actual',hint:'2',icon:<Check size={15}/>,run:()=>setLayer('actual')},{label:'Show weekly insights',hint:'I',icon:<BarChart3 size={15}/>,run:()=>showUtility('insights')},{label:'Search blocks',hint:'/',icon:<Search size={15}/>,run:()=>showUtility('search')},{label:'Open settings',hint:'',icon:<Settings2 size={15}/>,run:()=>showUtility('settings')}]
  const menuBlock=eventMenu?renderedBlocks.find(b=>b.id===eventMenu.id):undefined

  if(!store.ready)return <AppLoading/>
  return <main className="tempo-app" style={{'--ghost-opacity':data.settings.underlayOpacity/100,'--sidebar-w':`${leftWidth}px`,'--panel-w':`${rightWidth}px`} as React.CSSProperties}>
    {store.syncConflict&&<div className="confirm-backdrop" role="presentation"><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="sync-conflict-title"><AlertTriangle size={20}/><h2 id="sync-conflict-title">Changes overlap on another device</h2><p>Both versions changed {store.syncConflict.paths.length===1?'the same field':`${store.syncConflict.paths.length} of the same fields`}. Independent edits have already been combined. Choose which version wins only for the overlapping changes.</p><footer><button onClick={()=>store.resolveSyncConflict('remote')}>Use server version</button><button className="confirm-danger" onClick={()=>store.resolveSyncConflict('local')}>Keep this device</button></footer></div></div>}
    <AppHeader layer={layer} view={view} range={rangeLabel(dates)} sidebarOpen={sidebarOpen} panel={utilityPanel} planLabel={data.settings.planLabel??'Plan'} actualLabel={data.settings.actualLabel??'Actual'} userFirstName={data.settings.userFirstName} userLastName={data.settings.userLastName} quote={data.currentQuote} hourScale={data.settings.hourScale} onLayer={v=>{editScopeRef.current=null;setLayer(v);setSelectedIds([]);setEventOpen(false);setDraftBlock(null)}} onRenameLayer={(target,name)=>store.patchSettings(target==='plan'?{planLabel:name}:{actualLabel:name})} onView={setView} onToggleSidebar={()=>setSidebarOpen(v=>!v)} onNavigate={navigate} onToday={()=>setAnchor(new Date())} onPanel={showUtility} onCommand={()=>setCommandOpen(true)} onPatchSettings={store.patchSettings} onQuote={store.setQuote} onNextQuote={store.nextQuote} onCopyPlan={()=>copyPlan()}/>
    <div className="app-body">{sidebarOpen&&<><Sidebar anchor={anchor} categories={data.categories} groups={data.groups} defaultCategoryId={data.settings.defaultCategoryId} panel={utilityPanel} userFirstName={data.settings.userFirstName} userLastName={data.settings.userLastName} userEmail={user.email??''} syncStatus={store.syncStatus} onSignOut={onSignOut} onAnchor={setAnchor} onToggleCategory={store.toggleCategory} onToggleGroup={store.toggleGroup} onApplyCategoryLayout={store.applyCategoryLayout} onReorderGroup={store.reorderGroups} onRenameGroup={store.renameGroup} onAddGroup={store.createGroup} onRename={store.renameCategory} onAdd={store.createCategory} onColor={store.colorCategory} onDefault={store.setDefaultCategory} onDelete={store.deleteCategory} onMerge={store.mergeCategory} onNew={newBlock} onPanel={showUtility} onPatchSettings={store.patchSettings}/><ResizeHandle side="left" value={leftWidth} min={190} max={360} onResize={resizeLeft}/></>}<section className="calendar-workspace">{view==='month'?<MonthView anchor={anchor} blocks={renderedBlocks} categories={data.categories} layer={layer} onOpen={open} onDay={d=>{setAnchor(d);setView('day')}}/>:<WeekGrid dates={dates} blocks={renderedBlocks} categories={data.categories} settings={data.settings} layer={layer} selectedIds={selectedIds} onSelect={select} onSelectMany={selectMany} onClearSelection={clearSelection} onCreate={createDraft} onUpdate={requestBlockChange} onUpdateMany={store.updateBlocks} onOpen={open} onEventContext={(id,x,y)=>{if(!selectedIds.includes(id))setSelectedIds([id]);setEventMenu({id,x,y})}} onCopyPlanDay={date=>copyPlan([date])}/>}</section><ResizeHandle side="right" value={rightWidth} min={250} max={440} onResize={resizeRight}/>
      {activePanel==='event'&&selected&&<EventInspector block={selected} isDraft={draftBlock?.id===selected.id} categories={data.categories} groups={data.groups} settings={data.settings} onChange={changeBlock} onRecurrence={rule=>changeRecurrence(selected,rule)} onDelete={deleteSelected} onDuplicate={()=>duplicate(selected)} onCopyLayer={target=>copyLayer(selected,target)} onClose={closeEvent}/>} {activePanel==='insights'&&<InsightsPanel blocks={data.blocks} categories={data.categories} groups={data.groups} settings={data.settings} dates={dates} layer={layer}/>} {activePanel==='settings'&&<SettingsPanel settings={data.settings} data={data} deletedCalendars={data.deletedCalendars??[]} onRestore={store.restoreCategory} onPatch={store.patchSettings} onFormatAllTitles={formatAllTitles} onImport={next=>{try{store.replaceData(next);notify('Calendar imported')}catch{notify('That calendar file is not valid')}}} onReset={()=>{store.reset();notify('Demo calendar restored')}} onShortcuts={()=>showUtility('shortcuts')} onClose={closeUtility}/>} {activePanel==='search'&&<SearchPanel blocks={data.blocks} categories={data.categories} onOpen={b=>{setAnchor(new Date(`${b.date}T12:00:00`));setLayer(b.layer);open(b.id)}} onClose={closeUtility}/>} {activePanel==='shortcuts'&&<ShortcutsPanel onClose={()=>showUtility('settings')}/>}</div>
    {eventMenu&&menuBlock&&<EventMenu x={eventMenu.x} y={eventMenu.y} block={menuBlock} calendars={data.categories} groups={data.groups} selectionCount={selectedIds.length} autoFormatTitles={data.settings.autoFormatTitles} onRename={title=>changeBlock({...menuBlock,title})} onDuplicate={()=>{duplicateSelection();setEventMenu(null)}} onCopyLayer={target=>{store.addBlocks(selectedBlocks().map(b=>({...b,id:crypto.randomUUID(),layer:target,sourcePlanId:target==='actual'&&b.layer==='plan'?b.id:undefined,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined})));setEventMenu(null)}} onCalendar={id=>{const items=selectedBlocks();if(items.length===1)requestBlockChange({...items[0],categoryId:id});else store.updateBlocks(items.map(b=>({...b,categoryId:id})));setEventMenu(null)}} onDelete={()=>{deleteSelected();setEventMenu(null)}} onClose={()=>setEventMenu(null)}/>} {scopeRequest&&<RecurrenceScopeDialog action={scopeRequest.action} onChoose={scope=>{scopeRequest.run(scope);setScopeRequest(null)}} onClose={()=>{scopeRequest.cancel?.();setScopeRequest(null)}}/>} {commandOpen&&<CommandPalette actions={actions} onClose={()=>setCommandOpen(false)}/>} {store.undo&&<div className="undo-toast"><span>{store.undo.label}</span><button onClick={store.undoDelete}>Undo</button><button aria-label="Dismiss" onClick={()=>store.setUndo(null)}>×</button></div>} {toast&&<div className="app-toast">{toast}</div>}
  </main>
}
