'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { flushSync } from 'react-dom'
import type { User } from '@supabase/supabase-js'
import { AlertTriangle, BarChart3, CalendarDays, Check, Keyboard, ListTodo, Search, Settings2, Target } from 'lucide-react'
import { useCalendarStore } from '@/hooks/useCalendarStore'
import type { ResolvedTheme, ThemePreference } from '@/hooks/useTheme'
import { deriveLightCalendarColor } from '@/lib/calendar/color-model'
import { addDays, adjacentVisibleDay, rangeLabel, toISO, weekDates } from '@/lib/calendar/date'
import { toTitleCase } from '@/lib/calendar/title-case'
import { recurringScopeIds, resolveTodoLinkClick, shouldEndShiftLinking } from '@/lib/calendar/todo'
import { eventMatchesShortcut, formatShortcut, resolveShortcuts, shortcutDefinitions, withShortcutOverride } from '@/lib/calendar/shortcuts'
import type { CalendarBlock, Layer, Panel, RecurrenceRule, RecurrenceScope, ShortcutId, UtilityPanel, ViewMode, Weekday } from '@/lib/calendar/types'
import { AppHeader } from './AppHeader'
import { Sidebar } from './Sidebar'
import { WeekGrid } from './WeekGrid'
import { MonthView } from './MonthView'
import { EventInspector } from './EventInspector'
import { InsightsPanel } from './InsightsPanel'
import { TodoPanel } from './TodoPanel'
import { SettingsPanel } from './SettingsPanel'
import { SearchPanel } from './SearchPanel'
import { ShortcutsPanel } from './ShortcutsPanel'
import { CommandPalette } from './CommandPalette'
import { EventMenu } from './FloatingMenus'
import { ResizeHandle } from './ResizeHandle'

function RecurrenceScopeChoices({onFollowing,onAll}:{onFollowing:()=>void;onAll:()=>void}){return <><button onClick={onFollowing}>This and following</button><button onClick={onAll}>All events</button></>}
function readLegacyTodoPanelPreferences(){const title=localStorage.getItem('tempo-todo-panel-title')?.trim().slice(0,120);try{const raw=JSON.parse(localStorage.getItem('tempo-collapsed-todo-tabs')??'[]'),collapsedTabIds=Array.isArray(raw)?raw.filter((id):id is string=>typeof id==='string'):[];return{title,collapsedTabIds}}catch{return{title,collapsedTabIds:[] as string[]}}}

export function CalendarApp({user,onSignOut,theme,themePreference,onThemePreference}:{user:User;onSignOut:()=>void;theme:ResolvedTheme;themePreference:ThemePreference;onThemePreference:(preference:ThemePreference)=>void}){
  const store=useCalendarStore(user),{data}=store
  const [layer,setLayer]=useState<Layer>('actual'),[view,setView]=useState<ViewMode>('week'),[anchor,setAnchor]=useState(()=>new Date())
  const [utilityPanel,setUtilityPanel]=useState<UtilityPanel>(null),[eventOpen,setEventOpen]=useState(false),[sidebarOpen,setSidebarOpen]=useState(true)
  const [selectedIds,setSelectedIds]=useState<string[]>([]),[draftBlock,setDraftBlock]=useState<CalendarBlock|null>(null),[eventMenu,setEventMenu]=useState<{id:string;x:number;y:number}|null>(null)
  const [commandOpen,setCommandOpen]=useState(false),[toast,setToast]=useState('')
  const [recurringChangeToast,setRecurringChangeToast]=useState<({action:'edit'|'move'|'resize';original:CalendarBlock;next:CalendarBlock;commitId:string}|{action:'delete';original:CalendarBlock;commitId:string})|null>(null)
  const [linkingTodoId,setLinkingTodoId]=useState<string|null>(null),[recurringLinkToast,setRecurringLinkToast]=useState<{todoId:string;block:CalendarBlock;beforeLinks:string[];mode:'link'|'unlink';commitId:string}|null>(null)
  const [leftWidth,setLeftWidth]=useState(232),[rightWidth,setRightWidth]=useState(296)
  const blockClipboard=useRef<CalendarBlock[]>([])
  const editScopeRef=useRef<{id:string;scope:RecurrenceScope}|null>(null)
  const shiftClickedTodoRef=useRef<string|null>(null)
  const legacyTodoPanelPreferencesRef=useRef(false)
  const horizontalWheelRef=useRef({total:0,pending:0,timer:0,frame:0})
  const weekTransitionRef=useRef<ViewTransition|null>(null)
  const dates=useMemo(()=>view==='day'?[anchor]:weekDates(anchor,data.settings.showWeekends,data.settings.weekStartsOn),[anchor,view,data.settings.showWeekends,data.settings.weekStartsOn])
  const displayedWeekStartRef=useRef(dates[0]);displayedWeekStartRef.current=dates[0]
  const renderedBlocks=useMemo(()=>draftBlock?[...data.blocks,draftBlock]:data.blocks,[data.blocks,draftBlock])
  const nonEventCategories=useMemo(()=>theme==='light'?data.categories.map(category=>({...category,color:deriveLightCalendarColor(category.color,'nonEvent')})):data.categories,[data.categories,theme])
  const eventCategories=useMemo(()=>theme==='light'?data.categories.map(category=>({...category,color:deriveLightCalendarColor(category.color,'event')})):data.categories,[data.categories,theme])
  const nonEventDeletedCalendars=useMemo(()=>theme==='light'?(data.deletedCalendars??[]).map(item=>({...item,category:{...item.category,color:deriveLightCalendarColor(item.category.color,'nonEvent')}})):data.deletedCalendars??[],[data.deletedCalendars,theme])
  const selected=renderedBlocks.find(b=>b.id===selectedIds[selectedIds.length-1])
  const activePanel:Panel=eventOpen&&selected?'event':utilityPanel&&utilityPanel!=='insights'?utilityPanel:'insights'
  const resolvedShortcuts=useMemo(()=>resolveShortcuts(data.settings.keyboardShortcuts),[data.settings.keyboardShortcuts])

  const select=useCallback((id:string,additive:boolean)=>setSelectedIds(v=>additive?(v.includes(id)?v.filter(x=>x!==id):[...v,id]):[id]),[])
  const selectMany=useCallback((ids:string[])=>setSelectedIds(ids),[])
  const linkEventToTodo=useCallback((blockId:string,keepLinking=false)=>{if(!linkingTodoId)return false;const item=data.settings.todoItems?.find(candidate=>candidate.id===linkingTodoId),block=data.blocks.find(candidate=>candidate.id===blockId);if(!item||!block){setLinkingTodoId(null);return true}const beforeLinks=item.linkedBlockIds??[],click=resolveTodoLinkClick(item.id,beforeLinks,block.id,keepLinking);shiftClickedTodoRef.current=click.shiftClickedTodoId;if(click.alreadyLinked){if(click.closeImmediately)setLinkingTodoId(null);return true}const commitId=store.setTodoBlockLinks(item.id,click.nextLinkedBlockIds);if(click.closeImmediately)setLinkingTodoId(null);if(block.seriesId&&commitId)setRecurringLinkToast({todoId:item.id,block,beforeLinks,mode:'link',commitId});return true},[data.blocks,data.settings.todoItems,linkingTodoId,store])
  const openInspector=useCallback((id:string)=>{editScopeRef.current=null;setLinkingTodoId(null);setDraftBlock(current=>current&&current.id!==id?null:current);setSelectedIds([id]);setEventOpen(true);setEventMenu(null)},[])
  const open=useCallback((id:string,keepLinking=false)=>{if(linkEventToTodo(id,keepLinking))return;if(keepLinking&&view!=='month')return;openInspector(id)},[linkEventToTodo,openInspector,view])
  const showUtility=useCallback((next:Panel)=>{if(next==='event')return;editScopeRef.current=null;if(next!=='todos')setLinkingTodoId(null);setUtilityPanel(next);setEventOpen(false);setDraftBlock(null)},[])
  const toggleUtility=useCallback((next:Exclude<UtilityPanel,null>)=>{if(activePanel===next){if(next==='todos')setLinkingTodoId(null);setUtilityPanel(null);return}showUtility(next)},[activePanel,showUtility])
  const navigate=useCallback((n:number,oneDay=false)=>setAnchor(v=>view==='month'&&!oneDay?new Date(v.getFullYear(),v.getMonth()+n,1):addDays(v,n*(oneDay?1:view==='day'?1:7))),[view])
  const shiftWeekByDay=useCallback((direction:-1|1)=>{const next=adjacentVisibleDay(displayedWeekStartRef.current,direction,data.settings.showWeekends),apply=()=>{displayedWeekStartRef.current=next;setAnchor(next);store.patchSettings({weekStartsOn:((next.getDay()+6)%7) as Weekday})};if(!document.startViewTransition||window.matchMedia('(prefers-reduced-motion: reduce)').matches){apply();return}document.documentElement.dataset.weekDirection=direction>0?'next':'previous';const transition=document.startViewTransition(()=>flushSync(apply));weekTransitionRef.current=transition;transition.finished.finally(()=>{if(weekTransitionRef.current!==transition)return;weekTransitionRef.current=null;delete document.documentElement.dataset.weekDirection})},[data.settings.showWeekends,store.patchSettings])
  const createDraft=useCallback((input:Omit<CalendarBlock,'id'>)=>{const block={...input,id:crypto.randomUUID()};setDraftBlock(block);return block},[])
  const updateMany=useCallback((changes:CalendarBlock[])=>{const nextDraft=draftBlock?changes.find(block=>block.id===draftBlock.id):undefined;if(nextDraft)setDraftBlock(nextDraft);const persisted=changes.filter(block=>block.id!==draftBlock?.id);if(persisted.length)store.updateBlocks(persisted)},[draftBlock,store])
  const newBlock=useCallback(()=>{editScopeRef.current=null;const date=view==='month'?anchor:dates[0],block=createDraft({date:toISO(date),start:9,end:9+data.settings.defaultDuration,title:'',categoryId:data.settings.defaultCategoryId,layer});setSelectedIds([block.id]);setEventOpen(true)},[anchor,dates,view,layer,data.settings.defaultCategoryId,data.settings.defaultDuration,createDraft])
  const createMonthAllDay=useCallback((date:Date)=>{editScopeRef.current=null;const block=createDraft({date:toISO(date),start:0,end:24,title:'',categoryId:data.settings.defaultCategoryId,layer,allDay:true});setSelectedIds([block.id]);setEventOpen(true)},[createDraft,data.settings.defaultCategoryId,layer])
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),2400)}
  const copyPlan=(targetDates:string[]=dates.map(toISO))=>{const count=store.copyPlanToActual(targetDates);notify(count?`${count} planned ${count===1?'block':'blocks'} copied`:'Actual already matches this plan')}
  const deleteSelected=useCallback(()=>{if(!selectedIds.length)return;if(draftBlock&&selectedIds.includes(draftBlock.id))setDraftBlock(null);const persisted=selectedIds.filter(id=>id!==draftBlock?.id),single=persisted.length===1?data.blocks.find(b=>b.id===persisted[0]):undefined;if(single?.seriesId){const commitId=store.deleteRecurringBlock(single,'only');if(commitId)setRecurringChangeToast({action:'delete',original:single,commitId});setSelectedIds([]);setEventOpen(false);return}if(persisted.length)store.deleteBlocks(persisted);setSelectedIds([]);setEventOpen(false)},[selectedIds,draftBlock,data.blocks,store])
  const requestBlockChange=useCallback((next:CalendarBlock,action:'edit'|'move'|'resize'='edit')=>{const original=data.blocks.find(b=>b.id===next.id);if(!original?.seriesId){store.updateBlock(next);return}const changed=action==='resize'?original.start!==next.start||original.end!==next.end:action==='move'?original.date!==next.date||original.start!==next.start||original.end!==next.end:original.title!==next.title||original.notes!==next.notes||original.categoryId!==next.categoryId||original.start!==next.start||original.end!==next.end||original.date!==next.date;if(!changed)return;if(action==='edit'){if(original.categoryId!==next.categoryId){const catNext={...original,categoryId:next.categoryId};store.updateRecurringBlock(original,catNext,'all');return}const remembered=editScopeRef.current;if(remembered?.id===original.id){store.updateRecurringBlock(original,next,remembered.scope);return}}const commitId=store.updateRecurringBlock(original,next,'only');if(commitId)setRecurringChangeToast({action,original,next,commitId})},[data.blocks,store])
  const updateGridBlock=useCallback((next:CalendarBlock,action:'move'|'resize')=>{if(draftBlock?.id===next.id)setDraftBlock(next);else requestBlockChange(next,action)},[draftBlock,requestBlockChange])
  const changeBlock=useCallback((next:CalendarBlock)=>{if(draftBlock?.id===next.id){if(next.title!==''||next.categoryId!==data.settings.defaultCategoryId){store.addBlock(next);setDraftBlock(null)}else setDraftBlock(next)}else requestBlockChange(next)},[draftBlock,data.settings.defaultCategoryId,requestBlockChange,store])
  const changeRecurrence=useCallback((block:CalendarBlock,rule:RecurrenceRule|null)=>{editScopeRef.current=null;if(draftBlock?.id===block.id)setDraftBlock(null);store.setBlockRecurrence(block,rule)},[draftBlock,store])
  const closeEvent=()=>{editScopeRef.current=null;setEventOpen(false);setSelectedIds([]);setDraftBlock(null)}
  const clearSelection=useCallback(()=>{editScopeRef.current=null;setSelectedIds([]);setEventOpen(false);setDraftBlock(null)},[])
  const closeUtility=()=>setUtilityPanel(null)

  const selectedBlocks=useCallback(()=>data.blocks.filter(b=>selectedIds.includes(b.id)),[data.blocks,selectedIds])
  const duplicateSelection=useCallback(()=>{const source=selectedBlocks();if(!source.length)return;const copies=source.map(b=>({...b,id:crypto.randomUUID(),title:b.title?`${b.title} copy`:b.title,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined}));store.addBlocks(copies);setSelectedIds(copies.map(b=>b.id))},[selectedBlocks,store])
  const copySelection=useCallback(()=>{blockClipboard.current=structuredClone(selectedBlocks())},[selectedBlocks])
  const pasteSelection=useCallback(()=>{if(!blockClipboard.current.length)return;const offset=data.settings.snapMinutes/60;const copies=blockClipboard.current.map(b=>{const duration=b.end-b.start,start=Math.min(24-duration,b.start+offset);return {...b,id:crypto.randomUUID(),start,end:start+duration,layer,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined}});store.addBlocks(copies);setSelectedIds(copies.map(b=>b.id));setEventOpen(false)},[data.settings.snapMinutes,layer,store])
  const selectAllOfCalendars=useCallback(()=>{if(!selectedIds.length)return;const catIds=new Set(renderedBlocks.filter(b=>selectedIds.includes(b.id)).map(b=>b.categoryId));setSelectedIds(renderedBlocks.filter(b=>(b.allDay||b.layer===layer)&&dates.some(d=>toISO(d)===b.date)&&catIds.has(b.categoryId)&&(data.categories.find(c=>c.id===b.categoryId)?.visible??true)).map(b=>b.id))},[selectedIds,renderedBlocks,layer,dates,data.categories])

  useEffect(()=>{if(window.innerWidth<850)setSidebarOpen(false);const left=Number(localStorage.getItem('tempo-left-sidebar-width')),right=Number(localStorage.getItem('tempo-right-sidebar-width'));if(left)setLeftWidth(Math.max(190,Math.min(360,left)));if(right)setRightWidth(Math.max(250,Math.min(440,right)))},[])
  useEffect(()=>{if(view!=='week')return;const node=document.querySelector('.calendar-surface');if(!(node instanceof HTMLElement))return;const gesture=horizontalWheelRef.current,consume=()=>{gesture.frame=0;gesture.total+=gesture.pending;gesture.pending=0;const threshold=Math.max(56,Math.min(88,node.clientWidth/16));if(Math.abs(gesture.total)<threshold)return;const direction=gesture.total>0?1:-1;gesture.total-=direction*threshold;shiftWeekByDay(direction);if(Math.abs(gesture.total)>=threshold)gesture.frame=requestAnimationFrame(consume)},wheel=(event:WheelEvent)=>{if(event.ctrlKey)return;const unit=event.deltaMode===WheelEvent.DOM_DELTA_LINE?16:event.deltaMode===WheelEvent.DOM_DELTA_PAGE?node.clientWidth:1,x=event.deltaX*unit,y=event.deltaY*unit;if(Math.abs(x)<=Math.abs(y)||Math.abs(x)<3)return;event.preventDefault();window.clearTimeout(gesture.timer);gesture.timer=window.setTimeout(()=>{gesture.total=0;gesture.pending=0},140);gesture.pending+=x;if(!gesture.frame)gesture.frame=requestAnimationFrame(consume)};node.addEventListener('wheel',wheel,{passive:false});return()=>{node.removeEventListener('wheel',wheel);cancelAnimationFrame(gesture.frame);gesture.frame=0}},[shiftWeekByDay,view])
  useEffect(()=>()=>{window.clearTimeout(horizontalWheelRef.current.timer);cancelAnimationFrame(horizontalWheelRef.current.frame)},[])
  useEffect(()=>{if(!store.ready||legacyTodoPanelPreferencesRef.current)return;legacyTodoPanelPreferencesRef.current=true;const legacy=readLegacyTodoPanelPreferences(),validTabs=new Set((data.settings.todoTabs??[]).map(tab=>tab.id)),patch:{todoPanelTitle?:string;collapsedTodoTabIds?:string[]}={};if((data.settings.todoPanelTitle??'To-do list')==='To-do list'&&legacy.title)patch.todoPanelTitle=legacy.title;if(!(data.settings.collapsedTodoTabIds?.length)&&legacy.collapsedTabIds.length)patch.collapsedTodoTabIds=legacy.collapsedTabIds.filter(id=>validTabs.has(id));localStorage.removeItem('tempo-todo-panel-title');localStorage.removeItem('tempo-collapsed-todo-tabs');if(Object.keys(patch).length)store.patchSettings(patch)},[data.settings.collapsedTodoTabIds,data.settings.todoPanelTitle,data.settings.todoTabs,store.patchSettings,store.ready])
  const resizeLeft=(width:number)=>{setLeftWidth(width);localStorage.setItem('tempo-left-sidebar-width',String(Math.round(width)))}
  const resizeRight=(width:number)=>{setRightWidth(width);localStorage.setItem('tempo-right-sidebar-width',String(Math.round(width)))}
  useEffect(()=>{if(!store.undo)return;const timer=window.setTimeout(()=>store.setUndo(null),6000);return()=>window.clearTimeout(timer)},[store.undo,store.setUndo])
  useEffect(()=>{if(!recurringChangeToast)return;const timer=window.setTimeout(()=>setRecurringChangeToast(null),6000);return()=>window.clearTimeout(timer)},[recurringChangeToast])
  useEffect(()=>{if(!recurringLinkToast)return;const timer=window.setTimeout(()=>setRecurringLinkToast(null),6000);return()=>window.clearTimeout(timer)},[recurringLinkToast])
  useEffect(()=>{if(linkingTodoId&&!data.settings.todoItems?.some(item=>item.id===linkingTodoId))setLinkingTodoId(null)},[data.settings.todoItems,linkingTodoId])
  useEffect(()=>{if(!linkingTodoId){shiftClickedTodoRef.current=null;return}const todoId=linkingTodoId,blurLinkTrigger=()=>{const active=document.activeElement;if(active instanceof HTMLButtonElement&&active.closest('.todo-link-row'))active.blur()},stopIfShiftEnded=(event:KeyboardEvent|PointerEvent)=>{if(!shouldEndShiftLinking(shiftClickedTodoRef.current,todoId,event.shiftKey))return;shiftClickedTodoRef.current=null;blurLinkTrigger();setLinkingTodoId(current=>current===todoId?null:current)},stopOnBlur=()=>{if(shiftClickedTodoRef.current!==todoId)return;shiftClickedTodoRef.current=null;blurLinkTrigger();setLinkingTodoId(current=>current===todoId?null:current)};window.addEventListener('keyup',stopIfShiftEnded,true);window.addEventListener('pointermove',stopIfShiftEnded,true);window.addEventListener('blur',stopOnBlur);return()=>{window.removeEventListener('keyup',stopIfShiftEnded,true);window.removeEventListener('pointermove',stopIfShiftEnded,true);window.removeEventListener('blur',stopOnBlur)}},[linkingTodoId])
  useEffect(()=>{if(!store.ready)return;const handler=(e:KeyboardEvent)=>{const target=e.target as HTMLElement,isEditable=['INPUT','TEXTAREA','SELECT'].includes(target.tagName)||target.isContentEditable,definition=shortcutDefinitions.find(candidate=>eventMatchesShortcut(e,resolvedShortcuts[candidate.id])),assigned=definition?resolvedShortcuts[definition.id]:null;if(!definition||(isEditable&&(!definition.allowInEditable||!assigned?.split('+').includes('Mod')))||(e.repeat&&!['previousRange','nextRange','previousDay','nextDay'].includes(definition.id)))return;let handled=true;switch(definition.id){case'commandMenu':setCommandOpen(current=>!current);break;case'newBlock':newBlock();break;case'shortcuts':toggleUtility('shortcuts');break;case'closeClear':setCommandOpen(false);setLinkingTodoId(null);clearSelection();break;case'duplicateSelected':if(selectedIds.length)duplicateSelection();else handled=false;break;case'copySelected':if(selectedIds.length)copySelection();else handled=false;break;case'pasteBlocks':if(blockClipboard.current.length)pasteSelection();else handled=false;break;case'selectCalendarBlocks':if(selectedIds.length)selectAllOfCalendars();else handled=false;break;case'deleteSelected':if(selectedIds.length)deleteSelected();else handled=false;break;case'undo':store.undoHistory();break;case'redo':store.redoHistory();break;case'today':setAnchor(new Date());break;case'previousRange':navigate(-1);break;case'nextRange':navigate(1);break;case'previousDay':navigate(-1,true);break;case'nextDay':navigate(1,true);break;case'dayView':setView('day');break;case'weekView':setView('week');break;case'monthView':setView('month');break;case'actualLayer':setLayer('actual');break;case'planLayer':setLayer('plan');break;case'todos':toggleUtility('todos');break;case'insights':showUtility('insights');break;case'search':toggleUtility('search');break;case'settings':toggleUtility('settings');break}if(handled)e.preventDefault()};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[clearSelection,copySelection,deleteSelected,duplicateSelection,navigate,newBlock,pasteSelection,resolvedShortcuts,selectAllOfCalendars,selectedIds.length,showUtility,store,toggleUtility])

  const formatAllTitles=()=>{store.updateBlocks(data.blocks.filter(b=>b.title).map(b=>({...b,title:toTitleCase(b.title)})))}
  const duplicate=(source:CalendarBlock)=>{if(source.id===draftBlock?.id)return;store.createBlock({...source,title:`${source.title} copy`,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined})}
  const copyLayer=(source:CalendarBlock,target:Layer)=>{if(source.id===draftBlock?.id||source.allDay)return;store.createBlock({...source,layer:target,sourcePlanId:target==='actual'&&source.layer==='plan'?source.id:undefined,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined})}
  const hint=(id:ShortcutId)=>resolvedShortcuts[id]?formatShortcut(resolvedShortcuts[id]):''
  const actions=[{label:'Create new block',hint:hint('newBlock'),icon:<CalendarDays size={15}/>,run:newBlock},{label:'Go to today',hint:hint('today'),icon:<CalendarDays size={15}/>,run:()=>setAnchor(new Date())},{label:'Switch to Actual',hint:hint('actualLayer'),icon:<Check size={15}/>,run:()=>setLayer('actual')},{label:'Switch to Plan',hint:hint('planLayer'),icon:<Target size={15}/>,run:()=>setLayer('plan')},{label:'Open to-do list',hint:hint('todos'),icon:<ListTodo size={15}/>,run:()=>showUtility('todos')},{label:'Show weekly insights',hint:hint('insights'),icon:<BarChart3 size={15}/>,run:()=>showUtility('insights')},{label:'Search blocks',hint:hint('search'),icon:<Search size={15}/>,run:()=>showUtility('search')},{label:'Open settings',hint:hint('settings'),icon:<Settings2 size={15}/>,run:()=>showUtility('settings')},{label:'Keyboard shortcuts',hint:hint('shortcuts'),icon:<Keyboard size={15}/>,run:()=>showUtility('shortcuts')}]
  const menuBlock=eventMenu?renderedBlocks.find(b=>b.id===eventMenu.id):undefined
  const broadenRecurringChange=(scope:Exclude<RecurrenceScope,'only'>)=>{if(!recurringChangeToast)return;if(recurringChangeToast.action==='delete')store.deleteRecurringBlock(recurringChangeToast.original,scope,recurringChangeToast.commitId);else{store.updateRecurringBlock(recurringChangeToast.original,recurringChangeToast.next,scope,recurringChangeToast.commitId);if(recurringChangeToast.action==='edit')editScopeRef.current={id:recurringChangeToast.original.id,scope}}setRecurringChangeToast(null)}
  const broadenRecurringLink=(scope:Exclude<RecurrenceScope,'only'>)=>{if(!recurringLinkToast)return;const scoped=new Set(recurringScopeIds(data.blocks,recurringLinkToast.block,scope)),next=recurringLinkToast.mode==='link'?[...new Set([...recurringLinkToast.beforeLinks,...scoped])]:recurringLinkToast.beforeLinks.filter(id=>!scoped.has(id));store.setTodoBlockLinks(recurringLinkToast.todoId,next,recurringLinkToast.commitId);setRecurringLinkToast(null)}

  return <main className={`tempo-app${linkingTodoId?' link-mode':''}`} aria-busy={!store.ready} style={{'--ghost-opacity':data.settings.underlayOpacity/100,'--sidebar-w':`${leftWidth}px`,'--panel-w':`${rightWidth}px`} as React.CSSProperties}><div className="calendar-view" inert={!store.ready}>
    {store.syncConflict&&<div className="confirm-backdrop" role="presentation"><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="sync-conflict-title"><AlertTriangle size={20}/><h2 id="sync-conflict-title">Changes overlap on another device</h2><p>Both versions changed {store.syncConflict.paths.length===1?'the same field':`${store.syncConflict.paths.length} of the same fields`}. Independent edits have already been combined. Choose which version wins only for the overlapping changes.</p><footer><button onClick={()=>store.resolveSyncConflict('remote')}>Use server version</button><button className="confirm-danger" onClick={()=>store.resolveSyncConflict('local')}>Keep this device</button></footer></div></div>}
    <AppHeader layer={layer} view={view} range={view==='month'?anchor.toLocaleString('en',{month:'long',year:'numeric'}):rangeLabel(dates)} sidebarOpen={sidebarOpen} panel={utilityPanel} planLabel={data.settings.planLabel??'Plan'} actualLabel={data.settings.actualLabel??'Actual'} userFirstName={data.settings.userFirstName} userLastName={data.settings.userLastName} quote={data.currentQuote} hourScale={view==='month'?data.settings.monthScale:data.settings.hourScale} commandShortcut={resolvedShortcuts.commandMenu} todayShortcut={resolvedShortcuts.today} onLayer={v=>{editScopeRef.current=null;setLayer(v);setSelectedIds([]);setEventOpen(false);setDraftBlock(null)}} onRenameLayer={(target,name)=>store.patchSettings(target==='plan'?{planLabel:name}:{actualLabel:name})} onView={setView} onToggleSidebar={()=>setSidebarOpen(v=>!v)} onNavigate={navigate} onToday={()=>setAnchor(new Date())} onPanel={showUtility} onCommand={()=>setCommandOpen(true)} onPatchSettings={patch=>store.patchSettings(view==='month'&&patch.hourScale!=null?{monthScale:patch.hourScale}:patch)} onQuote={store.setQuote} onNextQuote={store.nextQuote} onCopyPlan={()=>copyPlan()}/>
    <div className="app-body">{sidebarOpen&&<><Sidebar anchor={anchor} weekStartsOn={data.settings.weekStartsOn} categories={nonEventCategories} sourceCategories={data.categories} groups={data.groups} defaultCategoryId={data.settings.defaultCategoryId} favoriteCategoryIds={data.settings.favoriteCategoryIds??[]} insightsExcludedCategoryIds={data.settings.insightsExcludedCategoryIds??[]} panel={utilityPanel} userFirstName={data.settings.userFirstName} userLastName={data.settings.userLastName} userEmail={user.email??''} syncStatus={store.syncStatus} onSignOut={onSignOut} onAnchor={setAnchor} onToggleCategory={store.toggleCategory} onToggleGroup={store.toggleGroup} onApplyCategoryLayout={store.applyCategoryLayout} onReorderGroup={store.reorderGroups} onRenameGroup={store.renameGroup} onAddGroup={store.createGroup} onRename={store.renameCategory} onAdd={store.createCategory} onColor={store.colorCategory} onDefault={store.setDefaultCategory} onDelete={store.deleteCategory} onMerge={store.mergeCategory} onNew={newBlock} onPanel={showUtility} onPatchSettings={store.patchSettings}/><ResizeHandle side="left" value={leftWidth} min={190} max={360} onResize={resizeLeft}/></>}<section className="calendar-workspace">{view==='month'?<MonthView anchor={anchor} weekStartsOn={data.settings.weekStartsOn} weekScale={data.settings.monthScale} blocks={renderedBlocks} categories={eventCategories} layer={layer} timeFormat={data.settings.timeFormat} favoriteCategoryIds={data.settings.favoriteCategoryIds??[]} onFocusMonth={setAnchor} onCreateAllDay={createMonthAllDay} onOpen={open} onDay={d=>{setAnchor(d);setView('week')}}/>:<WeekGrid dates={dates} blocks={renderedBlocks} categories={eventCategories} settings={data.settings} layer={layer} selectedIds={selectedIds} linking={!!linkingTodoId} onSelect={select} onSelectMany={selectMany} onClearSelection={clearSelection} onCreate={createDraft} onUpdate={updateGridBlock} onUpdateMany={updateMany} onOpen={open} onEventContext={(id,x,y)=>{if(!selectedIds.includes(id))setSelectedIds([id]);setEventMenu({id,x,y})}} onCopyPlanDay={date=>copyPlan([date])}/>}</section><ResizeHandle side="right" value={rightWidth} min={250} max={440} onResize={resizeRight}/>
      {activePanel==='event'&&selected&&<EventInspector block={selected} isDraft={draftBlock?.id===selected.id} categories={nonEventCategories} groups={data.groups} settings={data.settings} onChange={changeBlock} onRecurrence={rule=>changeRecurrence(selected,rule)} onDelete={deleteSelected} onDuplicate={()=>duplicate(selected)} onCopyLayer={target=>copyLayer(selected,target)} onClose={closeEvent}/>} {activePanel==='todos'&&<TodoPanel title={data.settings.todoPanelTitle??'To-do list'} collapsedTabIds={data.settings.collapsedTodoTabIds??[]} tabs={data.settings.todoTabs??[]} items={data.settings.todoItems??[]} blocks={data.blocks} categories={nonEventCategories} timeFormat={data.settings.timeFormat} linkingTodoId={linkingTodoId} onRenameTitle={todoPanelTitle=>store.patchSettings({todoPanelTitle})} onCollapsedTabsChange={collapsedTodoTabIds=>store.patchSettings({collapsedTodoTabIds})} onAddTab={store.createTodoTab} onRenameTab={store.renameTodoTab} onToggleFavoriteTab={store.toggleTodoTabFavorite} onDeleteTab={store.deleteTodoTab} onReorderTabs={store.reorderTodoTabs} onAddItem={store.createTodoItem} onUpdateItem={store.updateTodoItem} onDeleteItem={store.deleteTodoItem} onApplyItemLayout={store.applyTodoItemLayout} onLinkStart={id=>{setUtilityPanel('todos');setEventOpen(false);setSelectedIds([]);setDraftBlock(null);setLinkingTodoId(id)}} onCancelLink={()=>setLinkingTodoId(null)} onOpenEvent={openInspector}/>} {activePanel==='insights'&&<InsightsPanel blocks={data.blocks} categories={nonEventCategories} groups={data.groups} settings={data.settings} dates={dates} layer={layer}/>} {activePanel==='settings'&&<SettingsPanel settings={data.settings} data={data} deletedCalendars={nonEventDeletedCalendars} themePreference={themePreference} onThemePreference={onThemePreference} onRestore={store.restoreCategory} onPatch={store.patchSettings} onFormatAllTitles={formatAllTitles} onImport={next=>{try{store.replaceData(next);notify('Calendar imported')}catch{notify('That calendar file is not valid')}}} onReset={()=>{store.reset();notify('Demo calendar restored')}} onShortcuts={()=>showUtility('shortcuts')} onClose={closeUtility}/>} {activePanel==='search'&&<SearchPanel blocks={data.blocks} categories={nonEventCategories} onOpen={b=>{setAnchor(new Date(`${b.date}T12:00:00`));setLayer(b.layer);open(b.id)}} onClose={closeUtility}/>} {activePanel==='shortcuts'&&<ShortcutsPanel overrides={data.settings.keyboardShortcuts} onChange={(id,shortcut)=>store.patchSettings({keyboardShortcuts:withShortcutOverride(data.settings.keyboardShortcuts,id,shortcut)??{}})} onReset={()=>store.patchSettings({keyboardShortcuts:{}})} onClose={()=>showUtility('settings')}/>}</div>
    {eventMenu&&menuBlock&&<EventMenu x={eventMenu.x} y={eventMenu.y} block={menuBlock} calendars={nonEventCategories} groups={data.groups} selectionCount={selectedIds.length} autoFormatTitles={data.settings.autoFormatTitles} onRename={title=>changeBlock({...menuBlock,title})} onDuplicate={()=>{duplicateSelection();setEventMenu(null)}} onCopyLayer={target=>{const timed=selectedBlocks().filter(b=>!b.allDay);if(timed.length)store.addBlocks(timed.map(b=>({...b,id:crypto.randomUUID(),layer:target,sourcePlanId:target==='actual'&&b.layer==='plan'?b.id:undefined,seriesId:undefined,recurrence:undefined,occurrenceIndex:undefined,recurrenceDate:undefined,recurrenceStart:undefined,recurrenceEnd:undefined})));setEventMenu(null)}} onCalendar={id=>{if(selectedIds.length===1)changeBlock({...menuBlock,categoryId:id});else{const items=selectedBlocks();store.updateBlocks(items.map(b=>({...b,categoryId:id})))}setEventMenu(null)}} onDelete={()=>{deleteSelected();setEventMenu(null)}} onClose={()=>setEventMenu(null)}/>} {commandOpen&&<CommandPalette actions={actions} onClose={()=>setCommandOpen(false)}/>} {recurringChangeToast&&<div className="recurring-change-toast" role="status" aria-live="polite"><span>{recurringChangeToast.action==='edit'?'Edited':recurringChangeToast.action==='move'?'Moved':recurringChangeToast.action==='resize'?'Resized':'Deleted'} this event only</span><RecurrenceScopeChoices onFollowing={()=>broadenRecurringChange('following')} onAll={()=>broadenRecurringChange('all')}/><button onClick={()=>{store.undoCommit(recurringChangeToast.commitId);setRecurringChangeToast(null)}}>Undo</button><button aria-label="Dismiss" onClick={()=>setRecurringChangeToast(null)}>×</button></div>} {recurringLinkToast&&<div className="recurring-change-toast" role="status" aria-live="polite"><span>{recurringLinkToast.mode==='link'?'Linked':'Unlinked'} this event only</span><RecurrenceScopeChoices onFollowing={()=>broadenRecurringLink('following')} onAll={()=>broadenRecurringLink('all')}/><button onClick={()=>{store.undoCommit(recurringLinkToast.commitId);setRecurringLinkToast(null)}}>Undo</button><button aria-label="Dismiss" onClick={()=>setRecurringLinkToast(null)}>×</button></div>} {store.undo&&<div className="undo-toast"><span>{store.undo.label}</span><button onClick={store.undoDelete}>Undo</button><button aria-label="Dismiss" onClick={()=>store.setUndo(null)}>×</button></div>} {toast&&<div className="app-toast">{toast}</div>}</div>{!store.ready&&<><div className="loading-interaction-shield" aria-hidden="true"/><div className="loading-toast" role="status" aria-live="polite"><i aria-hidden="true"/><span><b>Loading your calendar…</b><small>Showing saved data while checking for updates.</small></span></div></>}
  </main>
}
