'use client'
import { useEffect, useState } from 'react'

const clamp=(n:number,min=0,max=255)=>Math.max(min,Math.min(max,n))
function hexToRgb(hex:string){const value=hex.replace('#','');if(!/^[0-9a-f]{6}$/i.test(value))return null;return {r:parseInt(value.slice(0,2),16),g:parseInt(value.slice(2,4),16),b:parseInt(value.slice(4,6),16)}}
function rgbToHex(r:number,g:number,b:number){return `#${[r,g,b].map(v=>Math.round(clamp(v)).toString(16).padStart(2,'0')).join('')}`.toUpperCase()}
function rgbToHsl(r:number,g:number,b:number){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0,s=0;if(d){s=d/(1-Math.abs(2*l-1));if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}return {h:Math.round((h+360)%360),s:Math.round(s*100),l:Math.round(l*100)}}
function hslToRgb(h:number,s:number,l:number){h=((h%360)+360)%360;s=clamp(s,0,100)/100;l=clamp(l,0,100)/100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else [r,g,b]=[c,0,x];return {r:Math.round((r+m)*255),g:Math.round((g+m)*255),b:Math.round((b+m)*255)}}
function parseColor(value:string){const text=value.trim(),hex=hexToRgb(text);if(hex)return rgbToHex(hex.r,hex.g,hex.b);const hsl=text.match(/^hsla?\(\s*(-?[\d.]+)(?:deg)?[ ,]+([\d.]+)%[ ,]+([\d.]+)%/i);if(!hsl)return null;const rgb=hslToRgb(+hsl[1],+hsl[2],+hsl[3]);return rgbToHex(rgb.r,rgb.g,rgb.b)}

export function ColorEditor({color,onChange}:{color:string;onChange:(color:string)=>void}){const rgb=hexToRgb(color)??{r:128,g:128,b:128},hsl=rgbToHsl(rgb.r,rgb.g,rgb.b),[hexText,setHexText]=useState(color.toUpperCase()),[hslText,setHslText]=useState('');useEffect(()=>{setHexText(color.toUpperCase());setHslText(`hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)`)},[color,rgb.r,rgb.g,rgb.b,hsl.h,hsl.s,hsl.l]);const commit=(value:string,restore:()=>void)=>{const parsed=parseColor(value);if(parsed)onChange(parsed);else restore()};const channel=(key:'r'|'g'|'b',value:number)=>onChange(rgbToHex(key==='r'?value:rgb.r,key==='g'?value:rgb.g,key==='b'?value:rgb.b));return <div className="color-editor"><div className="color-format-pair"><span className="color-preview" style={{background:color}}/><input aria-label="HEX color" value={hexText} onChange={e=>setHexText(e.target.value)} onBlur={()=>commit(hexText,()=>setHexText(color.toUpperCase()))} onKeyDown={e=>e.key==='Enter'&&e.currentTarget.blur()}/><input aria-label="HSL color" value={hslText} onChange={e=>setHslText(e.target.value)} onBlur={()=>commit(hslText,()=>setHslText(`hsl(${hsl.h}, ${hsl.s}%, ${hsl.l}%)`))} onKeyDown={e=>e.key==='Enter'&&e.currentTarget.blur()}/></div><div className="rgb-sliders">{(['r','g','b'] as const).map(key=><label key={key}><b>{key.toUpperCase()}</b><input aria-label={`${key.toUpperCase()} channel`} type="range" min="0" max="255" value={rgb[key]} onChange={e=>channel(key,+e.target.value)}/><span>{rgb[key]}</span></label>)}</div></div>}
