'use client'
import { CalendarPlus, Check, ChevronRight, Copy, FolderPlus, GitMerge, Palette, Pencil, Star, Trash2, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { CATEGORY_COLORS } from '@/lib/calendar/constants'
import type { CalendarBlock, CalendarCategory, CalendarGroup, Layer } from '@/lib/calendar/types'
import { GroupedCalendarList } from './GroupedCalendarList'
import { ColorEditor } from './ColorEditor'

function useDismiss(onClose:()=>void){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const down=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))onClose()};const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('pointerdown',down);window.addEventListener('keydown',key);return()=>{window.removeEventListener('pointerdown',down);window.removeEventListener('keydown',key)}},[onClose]);return ref}
const position=(x:number,y:number,width=230)=>({left:Math.max(6,Math.min(x,window.innerWidth-width-6)),top:Math.max(6,Math.min(y,window.innerHeight-350))})

type CalendarMenuProps={x:number;y:number;calendar:CalendarCategory;calendars:CalendarCategory[];groups:CalendarGroup[];isDefault:boolean;onRename:(name:string)=>void;onColor:(v:string)=>void;onDefault:()=>void;onDelete:()=>void;onMerge:(target:string)=>void;onClose:()=>void}
export function CalendarMenu(p:CalendarMenuProps){const [name,setName]=useState(p.calendar.name),[mergeOpen,setMergeOpen]=useState(false);const cancel=useRef(false);const commit=()=>{if(!cancel.current&&name!==p.calendar.name)p.onRename(name);cancel.current=false};const close=()=>{commit();p.onClose()};const ref=useDismiss(close);return <div ref={ref} className="floating-menu calendar-menu" style={position(p.x,p.y)} onContextMenu={e=>e.preventDefault()}>
  <div className="floating-menu-title"><i style={{background:p.calendar.color}}/><input aria-label="Calendar name" value={name} onChange={e=>setName(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}if(e.key==='Escape'){cancel.current=true;p.onClose()}}}/><button aria-label="Close calendar menu" onClick={close}><X size={13}/></button></div>
  <div className="menu-section-label"><Palette size={11}/>COLOR</div><div className="color-grid full-palette">{CATEGORY_COLORS.map(color=><button key={color} aria-label={`Use color ${color}`} className={color===p.calendar.color?'selected':''} style={{background:color}} onClick={()=>p.onColor(color)}>{color===p.calendar.color&&<Check size={9}/>}</button>)}</div><ColorEditor color={p.calendar.color} onChange={p.onColor}/>
  <div className="submenu-anchor" onPointerEnter={()=>setMergeOpen(true)} onPointerLeave={()=>setMergeOpen(false)}><button onClick={()=>setMergeOpen(v=>!v)}><GitMerge size={13}/><span>Merge into</span><ChevronRight size={12}/></button>{mergeOpen&&<div className="submenu-panel merge-popup"><GroupedCalendarList groups={p.groups} calendars={p.calendars} excludeId={p.calendar.id} onChoose={p.onMerge}/></div>}</div>
  <div className="menu-divider"/><div className="calendar-menu-actions"><button className={p.isDefault?'menu-checked':''} onClick={p.onDefault}><Star size={13}/><span>Make default</span></button><button className="menu-danger" onClick={p.onDelete}><Trash2 size={13}/><span>Delete</span></button></div>
</div>}

type GroupMenuProps={x:number;y:number;name:string;onRename:(name:string)=>void;onClose:()=>void}
export function GroupMenu(p:GroupMenuProps){const [name,setName]=useState(p.name);const ref=useDismiss(p.onClose);const commit=()=>{if(name.trim()&&name!==p.name)p.onRename(name);p.onClose()};return <div ref={ref} className="floating-menu group-menu" style={position(p.x,p.y,210)} onContextMenu={e=>e.preventDefault()}><div className="floating-menu-title"><Pencil size={12}/><input aria-label="Tab name" value={name} onChange={e=>setName(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}if(e.key==='Escape')p.onClose()}}/></div></div>}

export function CalendarAreaMenu({x,y,onAddCalendar,onAddGroup,onClose}:{x:number;y:number;onAddCalendar:()=>void;onAddGroup:()=>void;onClose:()=>void}){const ref=useDismiss(onClose);return <div ref={ref} className="floating-menu calendar-area-menu" style={position(x,y,210)} onContextMenu={e=>e.preventDefault()}><button onClick={()=>{onAddCalendar();onClose()}}><CalendarPlus size={13}/><span>New calendar</span></button><button onClick={()=>{onAddGroup();onClose()}}><FolderPlus size={13}/><span>New tab</span></button></div>}

type EventMenuProps={x:number;y:number;block:CalendarBlock;calendars:CalendarCategory[];groups:CalendarGroup[];selectionCount:number;onRename:(title:string)=>void;onDuplicate:()=>void;onCopyLayer:(layer:Layer)=>void;onCalendar:(id:string)=>void;onDelete:()=>void;onClose:()=>void}
export function EventMenu(p:EventMenuProps){const [title,setTitle]=useState(p.block.title),originalTitle=useRef(p.block.title);const ref=useDismiss(p.onClose);return <div ref={ref} className="floating-menu event-menu compact-event-menu" style={position(p.x,p.y)} onContextMenu={e=>e.preventDefault()}><div className="floating-menu-title event-menu-title"><i style={{background:p.calendars.find(c=>c.id===p.block.categoryId)?.color}}/><input aria-label="Event name" value={title} onFocus={()=>{originalTitle.current=p.block.title}} onChange={e=>{const next=e.target.value;setTitle(next);p.onRename(next)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){const previous=originalTitle.current;setTitle(previous);p.onRename(previous);p.onClose()}}}/></div><div className="menu-section-label">MOVE {p.selectionCount>1?`${p.selectionCount} BLOCKS`:'BLOCK'} TO</div><GroupedCalendarList groups={p.groups} calendars={p.calendars} selectedId={p.selectionCount===1?p.block.categoryId:undefined} onChoose={p.onCalendar}/><div className="menu-divider"/><div className="event-menu-actions"><button onClick={()=>p.onCopyLayer(p.block.layer==='plan'?'actual':'plan')}><Copy size={13}/><span>Copy to {p.block.layer==='plan'?'Actual':'Plan'}</span></button><button onClick={p.onDuplicate}><Copy size={13}/><span>Duplicate</span></button><button className="menu-danger" onClick={p.onDelete}><Trash2 size={13}/><span>Delete</span></button></div></div>}
