'use client'
import { CalendarPlus, Check, ChevronRight, Copy, FolderPlus, GitMerge, Heart, Palette, Pencil, Star, Trash2, X } from 'lucide-react'
import { useRef, useState } from 'react'
import { CATEGORY_COLORS } from '@/lib/calendar/constants'
import type { CalendarBlock, CalendarCategory, CalendarGroup, Layer } from '@/lib/calendar/types'
import { toTitleCase } from '@/lib/calendar/title-case'
import { GroupedCalendarList } from './GroupedCalendarList'
import { ColorEditor } from './ColorEditor'
import { useAnchoredMenuPosition, useDismiss, useViewportMenuPosition } from './FloatingMenuCore'

type CalendarMenuProps={x:number;y:number;calendar:CalendarCategory;calendars:CalendarCategory[];groups:CalendarGroup[];isDefault:boolean;isFavorite:boolean;onRename:(name:string)=>void;onColor:(v:string)=>void;onDefault:()=>void;onFavorite:()=>void;onDelete:()=>void;onMerge:(target:string)=>void;onClose:()=>void}
export function CalendarMenu(p:CalendarMenuProps){const [name,setName]=useState(p.calendar.name),[mergeOpen,setMergeOpen]=useState(false);const cancel=useRef(false),mergeAnchorRef=useRef<HTMLDivElement>(null),mergeRef=useRef<HTMLDivElement>(null);const commit=()=>{if(!cancel.current&&name!==p.calendar.name)p.onRename(name);cancel.current=false};const close=()=>{commit();p.onClose()};const ref=useDismiss(close),menuStyle=useViewportMenuPosition(ref,p.x,p.y),mergeStyle=useAnchoredMenuPosition(mergeAnchorRef,mergeRef,mergeOpen,{direction:'horizontal',width:176,crossOffset:-5});return <div ref={ref} className="floating-menu calendar-menu" style={menuStyle} onContextMenu={e=>e.preventDefault()}>
  <div className="floating-menu-title"><i style={{background:p.calendar.color}}/><input aria-label="Calendar name" value={name} onChange={e=>setName(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}if(e.key==='Escape'){cancel.current=true;p.onClose()}}}/><button aria-label="Close calendar menu" onClick={close}><X size={13}/></button></div>
  <div className="menu-section-label"><Palette size={11}/>COLOR</div><div className="color-grid full-palette">{CATEGORY_COLORS.map(color=><button key={color} aria-label={`Use color ${color}`} className={color===p.calendar.color?'selected':''} style={{background:color}} onClick={()=>p.onColor(color)}>{color===p.calendar.color&&<Check size={9}/>}</button>)}</div><ColorEditor color={p.calendar.color} onChange={p.onColor}/>
  <div ref={mergeAnchorRef} className="submenu-anchor" onPointerEnter={()=>setMergeOpen(true)} onPointerLeave={()=>setMergeOpen(false)}><button onClick={()=>setMergeOpen(v=>!v)}><GitMerge size={13}/><span>Merge into</span><ChevronRight size={12}/></button>{mergeOpen&&<div ref={mergeRef} className="submenu-panel merge-popup" style={mergeStyle}><GroupedCalendarList groups={p.groups} calendars={p.calendars} excludeId={p.calendar.id} onChoose={p.onMerge}/></div>}</div>
  <div className="menu-divider"/><div className="calendar-menu-actions"><button className={p.isDefault?'menu-checked':''} onClick={p.onDefault}><Star size={13}/><span>Make default</span></button><button className={p.isFavorite?'menu-checked':''} onClick={p.onFavorite}><Heart size={13}/><span>{p.isFavorite?'Favorited':'Favorite'}</span></button><button className="menu-danger" onClick={p.onDelete}><Trash2 size={13}/><span>Delete</span></button></div>
</div>}

type GroupMenuProps={x:number;y:number;name:string;onRename:(name:string)=>void;onClose:()=>void}
export function GroupMenu(p:GroupMenuProps){const [name,setName]=useState(p.name);const cancel=useRef(false);const commit=()=>{if(!cancel.current&&name.trim()&&name!==p.name)p.onRename(name);cancel.current=false};const close=()=>{commit();p.onClose()};const ref=useDismiss(close),menuStyle=useViewportMenuPosition(ref,p.x,p.y,210);return <div ref={ref} className="floating-menu group-menu" style={menuStyle} onContextMenu={e=>e.preventDefault()}><div className="floating-menu-title"><Pencil size={12}/><input aria-label="Tab name" value={name} onChange={e=>setName(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}if(e.key==='Escape'){cancel.current=true;p.onClose()}}}/></div></div>}

export function CalendarAreaMenu({x,y,onAddCalendar,onAddGroup,onClose}:{x:number;y:number;onAddCalendar:()=>void;onAddGroup:()=>void;onClose:()=>void}){const ref=useDismiss(onClose),menuStyle=useViewportMenuPosition(ref,x,y,210);return <div ref={ref} className="floating-menu calendar-area-menu" style={menuStyle} onContextMenu={e=>e.preventDefault()}><button onClick={()=>{onAddCalendar();onClose()}}><CalendarPlus size={13}/><span>New calendar</span></button><button onClick={()=>{onAddGroup();onClose()}}><FolderPlus size={13}/><span>New tab</span></button></div>}

type ProfileMenuProps={x:number;y:number;firstName:string;lastName:string;onSave:(firstName:string,lastName:string)=>void;onClose:()=>void}
export function ProfileMenu(p:ProfileMenuProps){const [first,setFirst]=useState(p.firstName),[last,setLast]=useState(p.lastName);const lastRef=useRef<HTMLInputElement>(null);const cancel=useRef(false);const commit=()=>{if(!cancel.current)p.onSave(first.trim(),last.trim());cancel.current=false};const close=()=>{commit();p.onClose()};const ref=useDismiss(close),menuStyle=useViewportMenuPosition(ref,p.x,p.y+8,220,undefined,true,20);return <div ref={ref} className="floating-menu profile-menu" style={menuStyle} onContextMenu={e=>e.preventDefault()}><div className="profile-field"><span>First name</span><input autoFocus value={first} onChange={e=>setFirst(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();lastRef.current?.focus()}if(e.key==='Escape'){cancel.current=true;p.onClose()}}}/></div><div className="profile-field"><span>Last name</span><input ref={lastRef} placeholder="optional" value={last} onChange={e=>setLast(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')close();if(e.key==='Escape'){cancel.current=true;p.onClose()}}}/></div></div>}

type EventMenuProps={x:number;y:number;block:CalendarBlock;calendars:CalendarCategory[];groups:CalendarGroup[];selectionCount:number;autoFormatTitles?:boolean;onRename:(title:string)=>void;onDuplicate:()=>void;onCopyLayer:(layer:Layer)=>void;onCalendar:(id:string)=>void;onDelete:()=>void;onClose:()=>void}
export function EventMenu(p:EventMenuProps){const [title,setTitle]=useState(p.block.title);const cancel=useRef(false);const commit=()=>{if(cancel.current){cancel.current=false;return};const next=p.autoFormatTitles&&title.trim()?toTitleCase(title):title;if(next!==p.block.title)p.onRename(next)};const ref=useDismiss(p.onClose),menuStyle=useViewportMenuPosition(ref,p.x,p.y-100,250,'.event-menu-calendar-scroll'),color=p.calendars.find(c=>c.id===p.block.categoryId)?.color;return <div ref={ref} className="floating-menu event-menu compact-event-menu" style={menuStyle} onContextMenu={e=>e.preventDefault()}><div className="floating-menu-title event-menu-title"><i style={{background:color}}/><input aria-label="Event name" value={title} onChange={e=>setTitle(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}if(e.key==='Escape'){cancel.current=true;p.onClose()}}}/></div><div className="event-menu-calendar-scroll"><GroupedCalendarList groups={p.groups} calendars={p.calendars} selectedId={p.selectionCount===1?p.block.categoryId:undefined} onChoose={p.onCalendar}/></div><div className="menu-divider"/><div className="event-menu-actions"><button onClick={()=>p.onCopyLayer(p.block.layer==='plan'?'actual':'plan')}><Copy size={13}/><span>Copy to {p.block.layer==='plan'?'Actual':'Plan'}</span></button><button onClick={p.onDuplicate}><Copy size={13}/><span>Duplicate</span></button><button className="menu-danger" onClick={p.onDelete}><Trash2 size={13}/><span>Delete</span></button></div></div>}
