'use client'
import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties, type RefObject } from 'react'

export type MenuDismissReason='outside'|'escape'
export function useDismiss(onClose:(reason:MenuDismissReason)=>void,active=true){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!active)return;const down=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))onClose('outside')},key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose('escape')};window.addEventListener('pointerdown',down);window.addEventListener('keydown',key);return()=>{window.removeEventListener('pointerdown',down);window.removeEventListener('keydown',key)}},[active,onClose]);return ref}
const menuLeft=(x:number,width:number,flipX:boolean,anchorInset:number)=>{const expandsLeft=flipX&&x+width>window.innerWidth-6;return Math.max(6,Math.min(expandsLeft?x-width+anchorInset:x-anchorInset,window.innerWidth-width-6))}
const position=(x:number,y:number,width=230,flipX=false,anchorInset=0)=>({left:menuLeft(x,width,flipX,anchorInset),top:Math.max(6,Math.min(y,window.innerHeight-350))})
export function useViewportMenuPosition(ref:RefObject<HTMLDivElement|null>,x:number,y:number,width=230,scrollSelector?:string,flipX=false,anchorInset=0){const[style,setStyle]=useState<CSSProperties>(()=>position(x,y,width,flipX,anchorInset));useLayoutEffect(()=>{const node=ref.current;if(!node)return;const place=()=>{const scrollRegion=scrollSelector?node.querySelector<HTMLElement>(scrollSelector):null,naturalHeight=node.scrollHeight-(scrollRegion?.clientHeight??0)+(scrollRegion?.scrollHeight??0),viewportHeight=window.innerHeight-12,height=Math.min(naturalHeight,viewportHeight),top=Math.max(6,Math.min(y,window.innerHeight-height-6)),left=menuLeft(x,width,flipX,anchorInset),clamped=naturalHeight>viewportHeight;setStyle({left,top,...(clamped?{maxHeight:viewportHeight,...(!scrollSelector?{overflowY:'auto',overscrollBehavior:'contain'}:{})}:{})})};place();const observer=new ResizeObserver(place);observer.observe(node);const scrollRegion=scrollSelector?node.querySelector<HTMLElement>(scrollSelector):null;if(scrollRegion)observer.observe(scrollRegion);window.addEventListener('resize',place);return()=>{observer.disconnect();window.removeEventListener('resize',place)}},[ref,x,y,width,scrollSelector,flipX,anchorInset]);return style}
type AnchoredMenuOptions={direction?:'vertical'|'horizontal';align?:'start'|'center'|'end';gap?:number;width?:number|'anchor';crossOffset?:number;viewportInset?:number}
export function useAnchoredMenuPosition(anchorRef:RefObject<HTMLElement|null>,menuRef:RefObject<HTMLDivElement|null>,open:boolean,{direction='vertical',align='start',gap=4,width,crossOffset=0,viewportInset=6}:AnchoredMenuOptions={}){const[style,setStyle]=useState<CSSProperties>({});useLayoutEffect(()=>{if(!open)return;const anchor=anchorRef.current,node=menuRef.current;if(!anchor||!node)return;const place=()=>{const rect=anchor.getBoundingClientRect(),viewportWidth=window.innerWidth,viewportHeight=window.innerHeight,naturalWidth=width==='anchor'?rect.width:width??node.scrollWidth,menuWidth=Math.min(naturalWidth,viewportWidth-viewportInset*2),naturalHeight=node.scrollHeight,maxViewportHeight=viewportHeight-viewportInset*2;let left:number,top:number,maxHeight=maxViewportHeight;if(direction==='horizontal'){const spaceRight=viewportWidth-rect.right-gap-viewportInset,spaceLeft=rect.left-gap-viewportInset,openRight=naturalWidth<=spaceRight||naturalWidth>spaceLeft&&spaceRight>=spaceLeft;left=openRight?rect.right+gap:rect.left-gap-menuWidth;top=rect.top+crossOffset}else{const spaceBelow=viewportHeight-rect.bottom-gap-viewportInset,spaceAbove=rect.top-gap-viewportInset,openBelow=naturalHeight<=spaceBelow||naturalHeight>spaceAbove&&spaceBelow>=spaceAbove;maxHeight=Math.max(0,openBelow?spaceBelow:spaceAbove);const renderedHeight=Math.min(naturalHeight,maxHeight);top=openBelow?rect.bottom+gap:rect.top-gap-renderedHeight;left=align==='center'?rect.left+(rect.width-menuWidth)/2:align==='end'?rect.right-menuWidth:rect.left;left+=crossOffset}left=Math.max(viewportInset,Math.min(left,viewportWidth-menuWidth-viewportInset));top=Math.max(viewportInset,Math.min(top,viewportHeight-Math.min(naturalHeight,maxHeight)-viewportInset));const clamped=naturalHeight>maxHeight;setStyle({position:'fixed',left,top,width:menuWidth,maxWidth:viewportWidth-viewportInset*2,...(clamped?{maxHeight,overflowY:'auto',overscrollBehavior:'contain'}:{maxHeight:undefined,overflowY:undefined,overscrollBehavior:undefined})})};place();const observer=new ResizeObserver(place);observer.observe(anchor);observer.observe(node);window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{observer.disconnect();window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true)}},[anchorRef,menuRef,open,direction,align,gap,width,crossOffset,viewportInset]);return style}
