'use client'
import { useRef, useState } from 'react'
import { ChevronDown, Monitor, Moon, RotateCcw, Settings2, Sun, X } from 'lucide-react'
import { CalendarDropdown } from './CalendarDropdown'
import { HourScaleSlider } from './HourScaleSlider'
import { GroupedCalendarList } from './GroupedCalendarList'
import { WeekdayPicker } from './WeekdayPicker'
import type { CalendarData, CalendarSettings, DeletedCalendar, Weekday } from '@/lib/calendar/types'
import type { ThemePreference } from '@/hooks/useTheme'

type Props={settings:CalendarSettings;data:CalendarData;deletedCalendars:DeletedCalendar[];themePreference:ThemePreference;onThemePreference:(preference:ThemePreference)=>void;onRestore:(id:string)=>void;onPatch:(p:Partial<CalendarSettings>)=>void;onFormatAllTitles:()=>void;onImport:(d:CalendarData)=>void;onReset:()=>void;onShortcuts:()=>void;onClose:()=>void}
export function SettingsPanel({settings,data,deletedCalendars,themePreference,onThemePreference,onRestore,onPatch,onFormatAllTitles,onImport,onReset,onShortcuts,onClose}:Props){
  const fileRef=useRef<HTMLInputElement>(null)
  const [resetConfirm,setResetConfirm]=useState(false),[insightsCalendarsOpen,setInsightsCalendarsOpen]=useState(false)
  const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='tempo-calendar.json';a.click();URL.revokeObjectURL(url)}
  const toggleInsightsCalendar=(id:string)=>{const excluded=settings.insightsExcludedCategoryIds??[];onPatch({insightsExcludedCategoryIds:excluded.includes(id)?excluded.filter(item=>item!==id):[...excluded,id]})}
  return <aside className="context-panel settings-panel"><div className="panel-head"><span><Settings2 size={15}/>Settings</span><button className="quiet-icon" aria-label="Close settings" onClick={onClose}><X size={16}/></button></div><div className="settings-body">
    <section><h3>Appearance</h3><div className="theme-options" role="radiogroup" aria-label="Color theme">{([{value:'system',label:'System',icon:Monitor},{value:'light',label:'Light',icon:Sun},{value:'dark',label:'Dark',icon:Moon}] as const).map(option=>{const Icon=option.icon;return <button key={option.value} type="button" role="radio" aria-checked={themePreference===option.value} className={themePreference===option.value?'active':''} onClick={()=>onThemePreference(option.value)}><Icon size={14}/><span>{option.label}</span></button>})}</div><p className="theme-help">{themePreference==='system'?'Follows this device’s appearance setting.':'Saved for this browser and applied immediately.'}</p></section>
    <section><h3>Calendar view</h3><label><span><b>Show weekends</b><small>Include Saturday and Sunday</small></span><input type="checkbox" checked={settings.showWeekends} onChange={e=>onPatch({showWeekends:e.target.checked})}/></label><div className="settings-week-start"><span><b>Start of week</b><small>First day shown in calendar views</small></span><WeekdayPicker label="Start of week" selected={[settings.weekStartsOn]} onToggle={day=>onPatch({weekStartsOn:day as Weekday})}/></div><label><span><b>Time format</b><small>Labels throughout the calendar</small></span><CalendarDropdown compact ariaLabel="Time format" value={settings.timeFormat} options={[{value:'12h',label:'12 hour'},{value:'24h',label:'24 hour'}]} onChange={timeFormat=>onPatch({timeFormat})}/></label><label><span><b>Hour density</b><small>Week and day scale · {settings.hourScale.toFixed(2)}×</small></span><HourScaleSlider aria-label="Hour density in settings" value={settings.hourScale} onChange={v=>onPatch({hourScale:v})}/></label><label><span><b>Month week density</b><small>Month row height · {settings.monthScale.toFixed(2)}×</small></span><HourScaleSlider aria-label="Month week density in settings" value={settings.monthScale} onChange={v=>onPatch({monthScale:v})}/></label></section>
    <section><h3>Day bounds</h3><label><span><b>Wake time</b><small>Start of available time</small></span><input type="number" min="0" max={settings.sleepHour-1} value={settings.wakeHour} onChange={e=>onPatch({wakeHour:+e.target.value})}/></label><label><span><b>Sleep time</b><small>End of available time</small></span><input type="number" min={settings.wakeHour+1} max="24" value={settings.sleepHour} onChange={e=>onPatch({sleepHour:+e.target.value})}/></label></section>
    <section><h3>Event titles</h3><label><span><b>Auto format titles</b><small>Apply title case to new &amp; renamed events</small></span><input type="checkbox" checked={!!settings.autoFormatTitles} onChange={e=>onPatch({autoFormatTitles:e.target.checked})}/></label><div className="data-actions"><button onClick={onFormatAllTitles}>Format all titles</button></div></section>
    <section><h3>Time blocking</h3><label><span><b>Snap interval</b><small>Pointer and keyboard precision</small></span><CalendarDropdown compact ariaLabel="Snap interval" value={settings.snapMinutes} options={[{value:5,label:'5 min'},{value:10,label:'10 min'},{value:15,label:'15 min'},{value:30,label:'30 min'}]} onChange={snapMinutes=>onPatch({snapMinutes:snapMinutes as CalendarSettings['snapMinutes']})}/></label><label><span><b>Default duration</b><small>Created on simple click</small></span><CalendarDropdown compact ariaLabel="Default duration" value={settings.defaultDuration} options={[{value:.5,label:'30 min'},{value:.75,label:'45 min'},{value:1,label:'1 hour'},{value:1.5,label:'1.5 hours'},{value:2,label:'2 hours'}]} onChange={defaultDuration=>onPatch({defaultDuration})}/></label><label><span><b>Plan underlay</b><small>Visibility in Actual</small></span><input type="range" min="6" max="100" value={settings.underlayOpacity} onChange={e=>onPatch({underlayOpacity:+e.target.value})}/></label></section>
    <section><h3>Weekly insights</h3><button type="button" className={`settings-dropdown-trigger ${insightsCalendarsOpen?'open':''}`} aria-expanded={insightsCalendarsOpen} aria-controls="insights-calendar-settings" onClick={()=>setInsightsCalendarsOpen(v=>!v)}><span><b>Excluded calendars</b><small>{settings.insightsExcludedCategoryIds?.length?`${settings.insightsExcludedCategoryIds.length} selected`:'None selected'}</small></span><ChevronDown size={14}/></button>{insightsCalendarsOpen&&<div id="insights-calendar-settings" className="insights-calendar-settings"><GroupedCalendarList groups={data.groups} calendars={data.categories} selectedIds={settings.insightsExcludedCategoryIds??[]} showHidden onChoose={toggleInsightsCalendar}/></div>}</section>
    <section><h3>Keyboard</h3><button className="settings-shortcuts" onClick={onShortcuts}>View keyboard shortcuts</button></section><section><h3>Recently deleted</h3><div className="settings-trash">{deletedCalendars.length===0?<p>No deleted calendars.</p>:deletedCalendars.map(item=><div key={item.category.id}><i style={{background:item.category.color}}/><span><b>{item.category.name}</b><small>{item.blocks.length} {item.blocks.length===1?'block':'blocks'}</small></span><button onClick={()=>onRestore(item.category.id)}><RotateCcw size={12}/>Restore</button></div>)}</div></section><section><h3>Local data</h3><div className="data-actions"><button onClick={exportData}>Export JSON</button><button onClick={()=>fileRef.current?.click()}>Import JSON</button></div><input ref={fileRef} type="file" accept="application/json" style={{display:'none'}} onChange={async e=>{const file=e.target.files?.[0];if(file)onImport(JSON.parse(await file.text()))}}/></section>
    <button className="reset-data" onClick={()=>setResetConfirm(true)}><RotateCcw size={14}/>Reset demo calendar</button></div>
    {resetConfirm&&<div className="confirm-backdrop" onPointerDown={()=>setResetConfirm(false)}><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="reset-calendar-title" onPointerDown={e=>e.stopPropagation()}><RotateCcw size={18}/><h2 id="reset-calendar-title">Reset to demo calendar?</h2><p className="confirm-warning">This will permanently delete all your blocks, calendars, and settings, replacing everything with the demo data. This cannot be undone.</p><footer><button onClick={()=>setResetConfirm(false)}>Cancel</button><button className="confirm-danger" autoFocus onClick={()=>{onReset();setResetConfirm(false)}}>Reset everything</button></footer></section></div>}
  </aside>
}
