import { RotateCcw, Settings2, X } from 'lucide-react'
import type { CalendarData, CalendarSettings } from '@/lib/calendar/types'

type Props={settings:CalendarSettings;data:CalendarData;onPatch:(p:Partial<CalendarSettings>)=>void;onImport:(d:CalendarData)=>void;onReset:()=>void;onClose:()=>void}
export function SettingsPanel({settings,data,onPatch,onImport,onReset,onClose}:Props){
  const exportData=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='tempo-calendar.json';a.click();URL.revokeObjectURL(url)}
  return <aside className="context-panel settings-panel"><div className="panel-head"><span><Settings2 size={15}/>Settings</span><button className="quiet-icon" aria-label="Close settings" onClick={onClose}><X size={16}/></button></div><div className="settings-body">
    <section><h3>Calendar view</h3><label><span><b>Show weekends</b><small>Include Saturday and Sunday</small></span><input type="checkbox" checked={settings.showWeekends} onChange={e=>onPatch({showWeekends:e.target.checked})}/></label><label><span><b>Time format</b><small>Labels throughout the calendar</small></span><select value={settings.timeFormat} onChange={e=>onPatch({timeFormat:e.target.value as '12h'|'24h'})}><option value="12h">12 hour</option><option value="24h">24 hour</option></select></label><label><span><b>Hour density</b><small>Vertical calendar scale</small></span><select value={settings.density} onChange={e=>onPatch({density:e.target.value as CalendarSettings['density']})}><option value="compact">Compact</option><option value="default">Default</option><option value="comfortable">Comfortable</option></select></label></section>
    <section><h3>Day bounds</h3><label><span><b>Wake time</b><small>Start of available time</small></span><input type="number" min="0" max={settings.sleepHour-1} value={settings.wakeHour} onChange={e=>onPatch({wakeHour:+e.target.value})}/></label><label><span><b>Sleep time</b><small>End of available time</small></span><input type="number" min={settings.wakeHour+1} max="24" value={settings.sleepHour} onChange={e=>onPatch({sleepHour:+e.target.value})}/></label></section>
    <section><h3>Time blocking</h3><label><span><b>Snap interval</b><small>Pointer and keyboard precision</small></span><select value={settings.snapMinutes} onChange={e=>onPatch({snapMinutes:+e.target.value as CalendarSettings['snapMinutes']})}><option value="5">5 min</option><option value="10">10 min</option><option value="15">15 min</option><option value="30">30 min</option></select></label><label><span><b>Default duration</b><small>Created on simple click</small></span><select value={settings.defaultDuration} onChange={e=>onPatch({defaultDuration:+e.target.value})}><option value="0.5">30 min</option><option value="0.75">45 min</option><option value="1">1 hour</option><option value="1.5">1.5 hours</option><option value="2">2 hours</option></select></label><label><span><b>Plan underlay</b><small>Visibility in Actual</small></span><input type="range" min="6" max="28" value={settings.underlayOpacity} onChange={e=>onPatch({underlayOpacity:+e.target.value})}/></label></section>
    <section><h3>Local data</h3><div className="data-actions"><button onClick={exportData}>Export JSON</button><label><span>Import JSON</span><input type="file" accept="application/json" onChange={async e=>{const file=e.target.files?.[0];if(file)onImport(JSON.parse(await file.text()))}}/></label></div></section>
    <button className="reset-data" onClick={onReset}><RotateCcw size={14}/>Reset demo calendar</button></div></aside>
}
