'use client'
import { DndContext, DragEndEvent, DragOverlay, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors } from '@dnd-kit/core'
import { SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { CalendarDays, ChevronLeft, ChevronRight, MoreHorizontal, Plus, Settings2, Star, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { addDays, startOfWeek, toISO } from '@/lib/calendar/date'
import type { CalendarCategory, CalendarGroup, Panel } from '@/lib/calendar/types'
import { CalendarMenu, GroupMenu } from './FloatingMenus'

type MenuState={kind:'calendar'|'group';id:string;x:number;y:number}|null
type Props={anchor:Date;categories:CalendarCategory[];groups:CalendarGroup[];defaultCategoryId:string;panel:Panel;onAnchor:(d:Date)=>void;onToggleCategory:(id:string)=>void;onToggleGroup:(id:string)=>void;onReorder:(source:string,target:string)=>void;onReorderGroup:(source:string,target:string)=>void;onRenameGroup:(id:string,name:string)=>void;onRename:(id:string,name:string)=>void;onAdd:()=>void;onColor:(id:string,color:string)=>void;onDefault:(id:string)=>void;onDelete:(id:string)=>void;onMerge:(source:string,target:string)=>void;onNew:()=>void;onPanel:(p:Panel)=>void}

function SortableCalendar({calendar,isDefault,onToggle,onMenu}:{calendar:CalendarCategory;isDefault:boolean;onToggle:()=>void;onMenu:(e:React.MouseEvent)=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:`cat:${calendar.id}`});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`calendar-toggle ${isDragging?'dragging':''} ${calendar.visible?'visible':'hidden'}`} {...attributes} {...listeners} onContextMenu={onMenu}><button className="color-square" aria-pressed={calendar.visible} aria-label={`${calendar.visible?'Hide':'Show'} ${calendar.name}`} style={{background:calendar.visible?calendar.color:'transparent',borderColor:calendar.color}} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onToggle()}}/><button className="calendar-name" onClick={e=>{e.stopPropagation();onToggle()}}>{calendar.name}</button>{isDefault&&<Star className="default-star" size={11}/>}<button className="calendar-more" aria-label={`More options for ${calendar.name}`} onPointerDown={e=>e.stopPropagation()} onClick={onMenu}><MoreHorizontal size={14}/></button></div>}

function SortableGroup({group,children,visible,onToggle,onMenu}:{group:CalendarGroup;children:React.ReactNode;visible:boolean;onToggle:()=>void;onMenu:(e:React.MouseEvent)=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:`group:${group.id}`});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`calendar-group ${isDragging?'dragging':''}`}><button className={`calendar-divider ${visible?'visible':''}`} {...attributes} {...listeners} onClick={onToggle} onContextMenu={onMenu}><span>{group.name}</span><i/><span className="group-state"/></button>{children}</div>}

export function Sidebar(p:Props){const {anchor,categories,groups,defaultCategoryId,panel}=p;const [menu,setMenu]=useState<MenuState>(null),[activeId,setActiveId]=useState<string|null>(null),[pendingDelete,setPendingDelete]=useState<CalendarCategory|null>(null);const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:7}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));const monthStart=new Date(anchor.getFullYear(),anchor.getMonth(),1),leading=(monthStart.getDay()+6)%7,days=new Date(anchor.getFullYear(),anchor.getMonth()+1,0).getDate(),selectedWeek=startOfWeek(anchor);const openMenu=(kind:'calendar'|'group',id:string,e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();setMenu({kind,id,x:e.clientX,y:e.clientY})};const menuCalendar=menu?.kind==='calendar'?categories.find(c=>c.id===menu.id):undefined,menuGroup=menu?.kind==='group'?groups.find(g=>g.id===menu.id):undefined;const onDragEnd=(e:DragEndEvent)=>{setActiveId(null);if(!e.over||e.active.id===e.over.id)return;const source=String(e.active.id),target=String(e.over.id);if(source.startsWith('group:')&&target.startsWith('group:'))p.onReorderGroup(source.slice(6),target.slice(6));if(source.startsWith('cat:')&&target.startsWith('cat:'))p.onReorder(source.slice(4),target.slice(4))}
  return <aside className="left-sidebar"><button className="create-button" onClick={p.onNew}><Plus size={16}/>Create block<kbd>N</kbd></button><section className="mini-calendar"><div className="mini-title"><b>{anchor.toLocaleString('en',{month:'long',year:'numeric'})}</b><span><button aria-label="Previous month" onClick={()=>p.onAnchor(new Date(anchor.getFullYear(),anchor.getMonth()-1,1))}><ChevronLeft size={14}/></button><button aria-label="Next month" onClick={()=>p.onAnchor(new Date(anchor.getFullYear(),anchor.getMonth()+1,1))}><ChevronRight size={14}/></button></span></div><div className="mini-weekdays">{'MTWTFSS'.split('').map((x,i)=><span key={i}>{x}</span>)}</div><div className="mini-days">{Array.from({length:leading},(_,i)=><i key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=new Date(anchor.getFullYear(),anchor.getMonth(),i+1),inWeek=date>=selectedWeek&&date<=addDays(selectedWeek,6),today=toISO(date)===toISO(new Date());return <button key={i} className={`${inWeek?'in-week ':''}${today?'today':''}`} onClick={()=>p.onAnchor(date)}>{i+1}</button>})}</div></section>
  <section className="sidebar-section compact-calendars"><div className="sidebar-heading"><span>CALENDARS</span><button aria-label="Add calendar" onClick={p.onAdd}><Plus size={13}/></button></div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={e=>setActiveId(String(e.active.id))} onDragCancel={()=>setActiveId(null)} onDragEnd={onDragEnd}><SortableContext items={groups.map(g=>`group:${g.id}`)} strategy={verticalListSortingStrategy}>{groups.map(group=>{const members=categories.filter(c=>c.groupId===group.id),allVisible=members.length>0&&members.every(c=>c.visible);return <SortableGroup key={group.id} group={group} visible={allVisible} onToggle={()=>p.onToggleGroup(group.id)} onMenu={e=>openMenu('group',group.id,e)}><SortableContext items={members.map(c=>`cat:${c.id}`)} strategy={verticalListSortingStrategy}>{members.map(c=><SortableCalendar key={c.id} calendar={c} isDefault={defaultCategoryId===c.id} onToggle={()=>p.onToggleCategory(c.id)} onMenu={e=>openMenu('calendar',c.id,e)}/>)}</SortableContext></SortableGroup>})}</SortableContext><DragOverlay>{activeId&&<div className="calendar-drag-overlay">{activeId.startsWith('group:')?groups.find(g=>g.id===activeId.slice(6))?.name:<><i style={{background:categories.find(c=>c.id===activeId.slice(4))?.color}}/>{categories.find(c=>c.id===activeId.slice(4))?.name}</>}</div>}</DragOverlay></DndContext></section>
  <nav className="sidebar-nav"/><div className="sidebar-bottom"><button className={`sidebar-settings ${panel==='settings'?'active':''}`} onClick={()=>p.onPanel('settings')}><Settings2 size={15}/>Settings</button><div className="sidebar-account"><div>TK</div><span><b>Local workspace</b><small>Saved on this device</small></span><CalendarDays size={15}/></div></div>
  {menuCalendar&&menu&&<CalendarMenu x={menu.x} y={menu.y} calendar={menuCalendar} calendars={categories} groups={groups} isDefault={defaultCategoryId===menuCalendar.id} onRename={name=>p.onRename(menuCalendar.id,name)} onColor={color=>p.onColor(menuCalendar.id,color)} onDefault={()=>{p.onDefault(menuCalendar.id);setMenu(null)}} onDelete={()=>{setPendingDelete(menuCalendar);setMenu(null)}} onMerge={target=>{p.onMerge(menuCalendar.id,target);setMenu(null)}} onClose={()=>setMenu(null)}/>} {menuGroup&&menu&&<GroupMenu x={menu.x} y={menu.y} name={menuGroup.name} onRename={name=>p.onRenameGroup(menuGroup.id,name)} onClose={()=>setMenu(null)}/>} {pendingDelete&&<div className="confirm-backdrop" onPointerDown={()=>setPendingDelete(null)}><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-calendar-title" onPointerDown={e=>e.stopPropagation()}><Trash2 size={18}/><h2 id="delete-calendar-title">Delete “{pendingDelete.name}”?</h2><p>Its events will move to Recently deleted and can be restored later.</p><footer><button onClick={()=>setPendingDelete(null)}>Cancel</button><button className="confirm-danger" autoFocus onClick={()=>{p.onDelete(pendingDelete.id);setPendingDelete(null)}}>Delete calendar</button></footer></section></div>}</aside>}
