'use client'
import { DndContext, DragEndEvent, DragOverlay, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors } from '@dnd-kit/core'
import { SortableContext, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, MoreHorizontal, Plus, Settings2, Star } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { addDays, startOfWeek, toISO } from '@/lib/calendar/date'
import type { CalendarCategory, CalendarGroup, Panel } from '@/lib/calendar/types'
import { CalendarMenu } from './FloatingMenus'

type MenuState={id:string;x:number;y:number}|null
type Props={anchor:Date;categories:CalendarCategory[];groups:CalendarGroup[];defaultCategoryId:string;panel:Panel;onAnchor:(d:Date)=>void;onToggleCategory:(id:string)=>void;onToggleGroup:(id:string)=>void;onReorder:(source:string,target:string)=>void;onRename:(id:string,name:string)=>void;onAdd:()=>void;onColor:(id:string,color:string)=>void;onDefault:(id:string)=>void;onDelete:(id:string)=>void;onMerge:(source:string,target:string)=>void;onNew:()=>void;onPanel:(p:Panel)=>void}

function SortableCalendar({calendar,isDefault,onToggle,onRename,onMenu}:{calendar:CalendarCategory;isDefault:boolean;onToggle:()=>void;onRename:(name:string)=>void;onMenu:(e:React.MouseEvent)=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:calendar.id});const [editing,setEditing]=useState(false),[name,setName]=useState(calendar.name);const cancel=useRef(false);useEffect(()=>setName(calendar.name),[calendar.name]);const commit=()=>{if(!cancel.current&&name!==calendar.name)onRename(name);cancel.current=false;setEditing(false)};return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`calendar-toggle ${isDragging?'dragging':''}`} {...attributes} {...listeners} onContextMenu={onMenu}><button className="color-square" aria-label={`${calendar.visible?'Hide':'Show'} ${calendar.name}`} style={{background:calendar.color}} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onToggle()}}/>{editing?<input className="calendar-name-input" autoFocus value={name} onPointerDown={e=>e.stopPropagation()} onChange={e=>setName(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){cancel.current=true;setName(calendar.name);e.currentTarget.blur()}}}/>:<button className="calendar-name" onPointerDown={e=>e.stopPropagation()} onClick={()=>setEditing(true)}>{calendar.name}</button>}{isDefault&&<Star className="default-star" size={10}/>}<button className="calendar-more" aria-label={`More options for ${calendar.name}`} onPointerDown={e=>e.stopPropagation()} onClick={onMenu}><MoreHorizontal size={14}/></button></div>}

export function Sidebar(p:Props){const {anchor,categories,groups,defaultCategoryId,panel}=p;const [menu,setMenu]=useState<MenuState>(null),[activeId,setActiveId]=useState<string|null>(null);const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:7}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));const monthStart=new Date(anchor.getFullYear(),anchor.getMonth(),1),leading=(monthStart.getDay()+6)%7,days=new Date(anchor.getFullYear(),anchor.getMonth()+1,0).getDate(),selectedWeek=startOfWeek(anchor);const openMenu=(id:string,e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();setMenu({id,x:e.clientX,y:e.clientY})};const menuCalendar=categories.find(c=>c.id===menu?.id);const onDragEnd=(e:DragEndEvent)=>{setActiveId(null);if(e.over&&e.active.id!==e.over.id)p.onReorder(String(e.active.id),String(e.over.id))}
  return <aside className="left-sidebar"><button className="create-button" onClick={p.onNew}><Plus size={16}/>Create block<kbd>N</kbd></button><section className="mini-calendar"><div className="mini-title"><b>{anchor.toLocaleString('en',{month:'long',year:'numeric'})}</b><span><button aria-label="Previous month" onClick={()=>p.onAnchor(new Date(anchor.getFullYear(),anchor.getMonth()-1,1))}><ChevronLeft size={14}/></button><button aria-label="Next month" onClick={()=>p.onAnchor(new Date(anchor.getFullYear(),anchor.getMonth()+1,1))}><ChevronRight size={14}/></button></span></div><div className="mini-weekdays">{'MTWTFSS'.split('').map((x,i)=><span key={i}>{x}</span>)}</div><div className="mini-days">{Array.from({length:leading},(_,i)=><i key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=new Date(anchor.getFullYear(),anchor.getMonth(),i+1),inWeek=date>=selectedWeek&&date<=addDays(selectedWeek,6),today=toISO(date)===toISO(new Date());return <button key={i} className={`${inWeek?'in-week ':''}${today?'today':''}`} onClick={()=>p.onAnchor(date)}>{i+1}</button>})}</div></section>
  <section className="sidebar-section compact-calendars"><div className="sidebar-heading"><span>CALENDARS</span><button aria-label="Add calendar" onClick={p.onAdd}><Plus size={13}/></button></div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={e=>setActiveId(String(e.active.id))} onDragCancel={()=>setActiveId(null)} onDragEnd={onDragEnd}>{groups.map(group=>{const members=categories.filter(c=>c.groupId===group.id),allVisible=members.every(c=>c.visible);return <div className="calendar-group" key={group.id}><button className="calendar-divider" onClick={()=>p.onToggleGroup(group.id)}><span>{group.name}</span><i/>{allVisible?<Check size={9}/>:<span className="mixed-dot"/>}</button><SortableContext items={members.map(c=>c.id)} strategy={verticalListSortingStrategy}>{members.map(c=><SortableCalendar key={c.id} calendar={c} isDefault={defaultCategoryId===c.id} onToggle={()=>p.onToggleCategory(c.id)} onRename={name=>p.onRename(c.id,name)} onMenu={e=>openMenu(c.id,e)}/>)}</SortableContext></div>})}<DragOverlay>{activeId&&<div className="calendar-drag-overlay"><i style={{background:categories.find(c=>c.id===activeId)?.color}}/>{categories.find(c=>c.id===activeId)?.name}</div>}</DragOverlay></DndContext></section>
  <nav className="sidebar-nav"/><div className="sidebar-bottom"><button className={`sidebar-settings ${panel==='settings'?'active':''}`} onClick={()=>p.onPanel('settings')}><Settings2 size={15}/>Settings</button><div className="sidebar-account"><div>TK</div><span><b>Local workspace</b><small>Saved on this device</small></span><CalendarDays size={15}/></div></div>
  {menu&&menuCalendar&&<CalendarMenu x={menu.x} y={menu.y} calendar={menuCalendar} calendars={categories} isDefault={defaultCategoryId===menuCalendar.id} onColor={color=>p.onColor(menuCalendar.id,color)} onDefault={()=>{p.onDefault(menuCalendar.id);setMenu(null)}} onDelete={()=>{p.onDelete(menuCalendar.id);setMenu(null)}} onMerge={target=>{p.onMerge(menuCalendar.id,target);setMenu(null)}} onClose={()=>setMenu(null)}/>}</aside>}
