'use client'
import { DndContext, DragEndEvent, DragOverEvent, DragOverlay, KeyboardSensor, PointerSensor, closestCenter, pointerWithin, rectIntersection, useSensor, useSensors } from '@dnd-kit/core'
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { CalendarDays, ChevronLeft, ChevronRight, GitMerge, MoreHorizontal, Plus, Settings2, Star, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { addDays, startOfWeek, toISO } from '@/lib/calendar/date'
import type { CalendarCategory, CalendarGroup, CalendarSettings, Panel } from '@/lib/calendar/types'
import { CalendarAreaMenu, CalendarMenu, GroupMenu, ProfileMenu } from './FloatingMenus'

const initials=(f?:string,l?:string)=>((f?.trim()[0]??'')+(l?.trim()[0]??'')).toUpperCase()||'?'

type MenuState={kind:'calendar'|'group';id:string;x:number;y:number}|{kind:'area';x:number;y:number}|null
type Props={anchor:Date;categories:CalendarCategory[];groups:CalendarGroup[];defaultCategoryId:string;panel:Panel;userFirstName?:string;userLastName?:string;onAnchor:(d:Date)=>void;onToggleCategory:(id:string)=>void;onToggleGroup:(id:string)=>void;onApplyCategoryLayout:(layout:{id:string;groupId?:string}[])=>void;onReorderGroup:(source:string,target:string)=>void;onRenameGroup:(id:string,name:string)=>void;onAddGroup:()=>void;onRename:(id:string,name:string)=>void;onAdd:()=>void;onColor:(id:string,color:string)=>void;onDefault:(id:string)=>void;onDelete:(id:string)=>void;onMerge:(source:string,target:string)=>void;onNew:()=>void;onPanel:(p:Panel)=>void;onPatchSettings:(patch:Partial<CalendarSettings>)=>void}

function SortableCalendar({calendar,isDefault,onToggle,onMenu}:{calendar:CalendarCategory;isDefault:boolean;onToggle:()=>void;onMenu:(e:React.MouseEvent)=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:`cat:${calendar.id}`});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`calendar-toggle ${isDragging?'dragging':''} ${calendar.visible?'visible':'hidden'}`} {...attributes} {...listeners} onContextMenu={onMenu}><button className="color-square" aria-pressed={calendar.visible} aria-label={`${calendar.visible?'Hide':'Show'} ${calendar.name}`} style={{background:calendar.visible?calendar.color:'transparent',borderColor:calendar.color}} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onToggle()}}/><button className="calendar-name" onClick={e=>{e.stopPropagation();onToggle()}}>{calendar.name}</button>{isDefault&&<Star className="default-star" size={11}/>}<button className="calendar-more" aria-label={`More options for ${calendar.name}`} onPointerDown={e=>e.stopPropagation()} onClick={onMenu}><MoreHorizontal size={14}/></button></div>}

function SortableGroup({group,children,visible,empty,onToggle,onMenu}:{group:CalendarGroup;children:React.ReactNode;visible:boolean;empty:boolean;onToggle:()=>void;onMenu:(e:React.MouseEvent)=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:`group:${group.id}`});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`calendar-group ${isDragging?'dragging':''}`}><button className={`calendar-divider ${visible?'visible':''}`} {...attributes} {...listeners} onClick={onToggle} onContextMenu={onMenu}><span>{group.name}</span><i/><span className="group-state"/></button>{children}{empty&&<div className="calendar-group-empty-drop"/>}</div>}

export function Sidebar(p:Props){
  const {anchor,categories,groups,defaultCategoryId,panel,userFirstName,userLastName}=p
  const [menu,setMenu]=useState<MenuState>(null),[activeId,setActiveId]=useState<string|null>(null),[preview,setPreview]=useState<CalendarCategory[]|null>(null),[pendingDelete,setPendingDelete]=useState<CalendarCategory|null>(null),[pendingMerge,setPendingMerge]=useState<{source:CalendarCategory;targetId:string}|null>(null),[profileMenu,setProfileMenu]=useState<{x:number;y:number}|null>(null)
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}))
  const monthStart=new Date(anchor.getFullYear(),anchor.getMonth(),1),leading=(monthStart.getDay()+6)%7,days=new Date(anchor.getFullYear(),anchor.getMonth()+1,0).getDate(),selectedWeek=startOfWeek(anchor)
  const openMenu=(kind:'calendar'|'group',id:string,e:React.MouseEvent)=>{e.preventDefault();e.stopPropagation();setMenu({kind,id,x:e.clientX,y:e.clientY})}
  const menuCalendar=menu?.kind==='calendar'?categories.find(c=>c.id===menu.id):undefined,menuGroup=menu?.kind==='group'?groups.find(g=>g.id===menu.id):undefined
  const shown=preview??categories
  const targetGroupFor=(target:string,list=shown)=>target.startsWith('group:')?target.slice(6):target.startsWith('cat:')?list.find(c=>c.id===target.slice(4))?.groupId:null
  const onDragOver=(e:DragOverEvent)=>{const source=String(e.active.id),target=e.over?String(e.over.id):'',items=preview??categories;if(!source.startsWith('cat:')||!target)return;const sourceId=source.slice(4),sourceItem=items.find(c=>c.id===sourceId),targetGroup=targetGroupFor(target,items);if(!sourceItem||!targetGroup||sourceItem.groupId===targetGroup)return;const without=items.filter(c=>c.id!==sourceId),overIndex=target.startsWith('cat:')?without.findIndex(c=>c.id===target.slice(4)):-1,insertAt=overIndex>=0?overIndex:without.reduce((last,c,index)=>c.groupId===targetGroup?index:last,-1)+1,next=[...without];next.splice(insertAt<0?next.length:insertAt,0,{...sourceItem,groupId:targetGroup});setPreview(next)}
  const finishDrag=(e:DragEndEvent)=>{const source=String(e.active.id),target=e.over?String(e.over.id):'',working=preview??categories;setActiveId(null);setPreview(null);if(!target)return;if(source.startsWith('group:')){const group=targetGroupFor(target);if(group&&group!==source.slice(6))p.onReorderGroup(source.slice(6),group);return}if(!source.startsWith('cat:'))return;const sourceId=source.slice(4),from=working.findIndex(c=>c.id===sourceId);if(from<0)return;let finalItems=working;if(target.startsWith('cat:')){const to=working.findIndex(c=>c.id===target.slice(4));if(to>=0&&to!==from)finalItems=arrayMove(working,from,to)}else if(target.startsWith('group:')){const groupId=target.slice(6);finalItems=working.map(c=>c.id===sourceId?{...c,groupId}:c)}p.onApplyCategoryLayout(finalItems.map(c=>({id:c.id,groupId:c.groupId})))}
  const collisions=(args:Parameters<typeof pointerWithin>[0])=>{const hits=pointerWithin(args).length?pointerWithin(args):(rectIntersection(args).length?rectIntersection(args):closestCenter(args));if(!String(args.active.id).startsWith('group:'))return hits;const hit=hits[0];if(!hit)return hits;const group=targetGroupFor(String(hit.id),categories);return group?[{...hit,id:`group:${group}`}]:hits}

  return <aside className="left-sidebar"><section className="mini-calendar"><div className="mini-title"><b>{anchor.toLocaleString('en',{month:'long',year:'numeric'})}</b><span><button aria-label="Previous month" onClick={()=>p.onAnchor(new Date(anchor.getFullYear(),anchor.getMonth()-1,1))}><ChevronLeft size={14}/></button><button aria-label="Next month" onClick={()=>p.onAnchor(new Date(anchor.getFullYear(),anchor.getMonth()+1,1))}><ChevronRight size={14}/></button></span></div><div className="mini-weekdays">{'MTWTFSS'.split('').map((x,i)=><span key={i}>{x}</span>)}</div><div className="mini-days">{Array.from({length:leading},(_,i)=><i key={`e${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=new Date(anchor.getFullYear(),anchor.getMonth(),i+1),inWeek=date>=selectedWeek&&date<=addDays(selectedWeek,6),today=toISO(date)===toISO(new Date());return <button key={i} className={`${inWeek?'in-week ':''}${today?'today':''}`} onClick={()=>p.onAnchor(date)}>{i+1}</button>})}</div></section>
    <section className="sidebar-section compact-calendars" onContextMenu={e=>{if((e.target as HTMLElement).closest('.calendar-toggle,.calendar-divider,.sidebar-heading button'))return;e.preventDefault();setMenu({kind:'area',x:e.clientX,y:e.clientY})}}><div className="sidebar-heading"><span>CALENDARS</span><button aria-label="Add calendar" onClick={p.onAdd}><Plus size={13}/></button></div><DndContext sensors={sensors} collisionDetection={collisions} onDragStart={e=>{setMenu(null);setActiveId(String(e.active.id));if(String(e.active.id).startsWith('cat:'))setPreview(categories.map(c=>({...c})))}} onDragOver={onDragOver} onDragCancel={()=>{setActiveId(null);setPreview(null)}} onDragEnd={finishDrag}><SortableContext items={groups.map(g=>`group:${g.id}`)} strategy={verticalListSortingStrategy}>{groups.map(group=>{const members=shown.filter(c=>c.groupId===group.id),allVisible=members.length>0&&members.every(c=>c.visible);return <SortableGroup key={group.id} group={group} visible={allVisible} empty={!members.length} onToggle={()=>p.onToggleGroup(group.id)} onMenu={e=>openMenu('group',group.id,e)}><SortableContext items={members.map(c=>`cat:${c.id}`)} strategy={verticalListSortingStrategy}>{members.map(c=><SortableCalendar key={c.id} calendar={c} isDefault={defaultCategoryId===c.id} onToggle={()=>p.onToggleCategory(c.id)} onMenu={e=>openMenu('calendar',c.id,e)}/>)}</SortableContext></SortableGroup>})}</SortableContext><DragOverlay dropAnimation={{duration:160,easing:'ease-out'}}>{activeId&&<div className="calendar-drag-overlay">{activeId.startsWith('group:')?groups.find(g=>g.id===activeId.slice(6))?.name:<><i style={{background:categories.find(c=>c.id===activeId.slice(4))?.color}}/>{categories.find(c=>c.id===activeId.slice(4))?.name}</>}</div>}</DragOverlay></DndContext></section>
    <nav className="sidebar-nav"/><div className="sidebar-bottom"><button className={`sidebar-settings ${panel==='settings'?'active':''}`} onClick={()=>p.onPanel('settings')}><Settings2 size={15}/>Settings</button><div className="sidebar-account"><div role="button" aria-label="Edit profile name" onClick={e=>setProfileMenu({x:e.clientX,y:e.clientY})}>{initials(userFirstName,userLastName)}</div><span><b>Local workspace</b><small>Saved on this device</small></span><CalendarDays size={15}/></div></div>
    {profileMenu&&<ProfileMenu x={profileMenu.x} y={profileMenu.y} firstName={userFirstName??''} lastName={userLastName??''} onSave={(f,l)=>p.onPatchSettings({userFirstName:f,userLastName:l})} onClose={()=>setProfileMenu(null)}/>}
    {menuCalendar&&menu&&<CalendarMenu x={menu.x} y={menu.y} calendar={menuCalendar} calendars={categories} groups={groups} isDefault={defaultCategoryId===menuCalendar.id} onRename={name=>p.onRename(menuCalendar.id,name)} onColor={color=>p.onColor(menuCalendar.id,color)} onDefault={()=>{p.onDefault(menuCalendar.id);setMenu(null)}} onDelete={()=>{setPendingDelete(menuCalendar);setMenu(null)}} onMerge={target=>{setPendingMerge({source:menuCalendar,targetId:target});setMenu(null)}} onClose={()=>setMenu(null)}/>} {menuGroup&&menu&&<GroupMenu x={menu.x} y={menu.y} name={menuGroup.name} onRename={name=>p.onRenameGroup(menuGroup.id,name)} onClose={()=>setMenu(null)}/>} {menu?.kind==='area'&&<CalendarAreaMenu x={menu.x} y={menu.y} onAddCalendar={p.onAdd} onAddGroup={p.onAddGroup} onClose={()=>setMenu(null)}/>} {pendingMerge&&<div className="confirm-backdrop" onPointerDown={()=>setPendingMerge(null)}><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="merge-calendar-title" onPointerDown={e=>e.stopPropagation()}><GitMerge size={18}/><h2 id="merge-calendar-title">Merge "{pendingMerge.source.name}"?</h2><p>Its events will move to "{categories.find(c=>c.id===pendingMerge.targetId)?.name}" and this calendar will be deleted.</p><footer><button onClick={()=>setPendingMerge(null)}>Cancel</button><button className="confirm-danger" autoFocus onClick={()=>{p.onMerge(pendingMerge.source.id,pendingMerge.targetId);setPendingMerge(null)}}>Merge calendar</button></footer></section></div>} {pendingDelete&&<div className="confirm-backdrop" onPointerDown={()=>setPendingDelete(null)}><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-calendar-title" onPointerDown={e=>e.stopPropagation()}><Trash2 size={18}/><h2 id="delete-calendar-title">Delete “{pendingDelete.name}”?</h2><p>Its events will move to Recently deleted and can be restored later.</p><footer><button onClick={()=>setPendingDelete(null)}>Cancel</button><button className="confirm-danger" autoFocus onClick={()=>{p.onDelete(pendingDelete.id);setPendingDelete(null)}}>Delete calendar</button></footer></section></div>}
  </aside>
}
